### ISSUE TITLE
Using attribute = 'class' and value at the same time?

### ISSUE THREAD

**Issue by kb1995** [pacocoursey/next-themes#100]
My theme provider definition

```
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            value={{
              light: "winter",
              dark: "halloween",
            }}
          >
```

And my toggle:

```
        <input
          onChange={(e) => {
            setTheme(e.target.checked ? "dark" : "light")
          }}
          defaultChecked={resolvedTheme === themes.dark}
          className="hidden"
          type="checkbox"
        />
```

However, the class attribute doesn't reflect correctly as I toggle it.

<img width="576" alt="Screenshot 2022-04-11 at 22 17 15" src="https://user-images.githubusercontent.com/32920882/162835073-0f36f55f-3e0a-4393-b1c8-04dfeb3d0363.png">
<img width="593" alt="Screenshot 2022-04-11 at 22 17 11" src="https://user-images.githubusercontent.com/32920882/162835079-d5de2f37-34c4-4dd7-bdf2-70657013933c.png">

I think the class should be light and dark, correct?

For context, I have several different names named winter, haloween etc, but I would like to integrate them with Tailwind so I'll need them to be named `light` and `dark` within the DOM

**Comment by pacocoursey** [comment]
The `value` prop is a mapping from theme name to DOM value. Here's the relevant part of the documentation for this: https://github.com/pacocoursey/next-themes#differing-dom-attribute-and-theme-name

In your case, it sounds like you want to reverse the value mapping?

```js
value={{
  winter: 'light',
  halloween: 'dark'
}}
```

When the theme is `winter`, the class will be `light`. When the theme is `halloween`, the class will be `dark`.

**Comment by kb1995** [comment]
@pacocoursey Thanks for the quick response. Unfortunately, I don't think it works as expected. If I don't set the class attribute (and keep it with data-theme) it does work perfectly well.

My updated ThemeProvider

```
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            value={{
              winter: "light",
              halloween: "dark",
            }}
          >
```

My Theme changer input

```
        <input
          onChange={(e) => {
            setTheme(e.target.checked ? "haloween" : "winter")
          }}
          defaultChecked={resolvedTheme === themes.dark}
          className="hidden"
          type="checkbox"
        />
```

However, these are the results I'm getting

<img width="599" alt="Screenshot 2022-04-12 at 09 10 39" src="https://user-images.githubusercontent.com/32920882/162913081-46afd633-d21c-4d9f-ab0b-22b81a7df0db.png">
<img width="588" alt="Screenshot 2022-04-12 at 09 10 43" src="https://user-images.githubusercontent.com/32920882/162913087-ce63dba0-bf3d-4b42-94ef-1bacc73d7ded.png">
