### ISSUE TITLE
ThemeProvider not work with multi layouts

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [pacocoursey/next-themes#102]
I use multi layouts in my project but I should add ThemeProvider every to getLayout method, But I want add ThemeProvider only in _app.ts file. How can fix or do that?

**Comment by pacocoursey** [comment]
Hey, I'm not sure I understand your question but can you try the solution in #81?

**Comment by Abdulrahmanelheyb** [comment]
Thanks for providing this solution, I solved 🤗
