### ISSUE TITLE
CSP issues in version 0.1.1

### ISSUE THREAD

**Issue by brokul-dev** [pacocoursey/next-themes#106]
Hello,
In version `0.1.1` there is still a problem with CSP `script-src` directive because it requires `data:` to work correctly.

I see that it's fixed in `0.2.0-beta.0`, and the `<script>` tag now renders inside the `<body>` element with normal content (not base64 encoded). With this in place, it's possible to add a hash exception to the CSP policy. Are there any plans to release it?

**Comment by dan2kx** [comment]
So how do we negate the CSP error in v0.2?

**Comment by brokul-dev** [comment]
@dan2kx, you could include the hash exception for the inline script in the CSP `script-src` directive. Alternatively, use `unsafe-inline`.

Option 1 (suggested): `script-src 'self' 'sha256-fDVtD703YIdPFRhb6ZJE/SvcwyA7gZRWfRRM6K6r9EA=';`
Option 2: `script-src 'self' 'unsafe-inline';`

**Comment by razzeee** [comment]
How would I create a new sha256 for the latest version?

**Comment by snaka** [comment]
@razzeee 

I ran the following code in the console of my browser to get the hash value.

```javascript
// Extract the content from the script element output by next-themes and store it in data
const script_content = document.querySelector('#__next > script').innerHTML,
    enc = new TextEncoder(),
    data = enc.encode(script_content);

// Function to encode the content of an array buffer to BASE64
function _arrayBufferToBase64( buffer ) {
    var binary = '';
    var bytes = new Uint8Array( buffer );
    var len = bytes.byteLength;
    for (var i = 0; i < len; i++) {
        binary += String.fromCharCode( bytes[ i ] );
    }
    return window.btoa( binary );
}

// Calculate the cryptographic digest from the content of data, and output it as a Hash value after encoding it with BASE64
crypto.subtle.digest('SHA-256', data).then(function(val){
  const digest = ["sha256", _arrayBufferToBase64(val)].join('-');
  console.log(`The digest for your script is: ${digest}`);
});
```

Ref. https://www.vector-logic.com/blog/posts/generating-csp-hash-from-browser-console
