### ISSUE TITLE
Unnecessary polyfill is included in client js by using Buffer API

### ISSUE THREAD

**Issue by nissy-dev** [pacocoursey/next-themes#107]
next-themes uses `Buffer` API for base64 encode when server-side rendering. 

https://github.com/pacocoursey/next-themes/blob/6f6e0ffeaef6a591ddc127290a36ece877152a9b/src/index.tsx#L304

However, this line increases a bundle size of client js. The polyfill of Buffer API is not necessary, but `_app.js` includes it.

![SS_ 2022-05-04 18 13 31](https://user-images.githubusercontent.com/17228098/166684157-22bb5aff-9d99-4758-97b9-48be1d0fd976.png)

I suggest two ways of solving this issue.

1. Stop using base64. I seem the PR #89 will solve.
2. Drop supporting Node.js v14 and below. atob/btoa is available in Node.js v16 and later.

@pacocoursey 
Will you continue to work about #89 ?

**Comment by pacocoursey** [comment]
Yes, I plan to move away from the base64 approach. Now that Next.js 12.1.6 is out, we can go back to using an inline script with `beforeInteractive`.

So this should be resolved with #89.
