### ISSUE TITLE
Cannot get resolvedTheme as "system"

### ISSUE THREAD

**Issue by surjithctly** [pacocoursey/next-themes#116]
I'm using in a Next.js/Tailwind Project. I added the themeswitch given in the hydration example. 

But when I change the theme, dark & light works correctly. But when I choose System, it still shows dark. Why its not showing "system", so user knows its auto. See below GIF. 

![CleanShot 2022-05-19 at 19 40 37](https://user-images.githubusercontent.com/1884712/169314418-9a714423-f17c-4d85-83c2-267ccace7e3d.gif)

code: 

```jsx
// _app.js
import { ThemeProvider } from "next-themes";
import "../css/tailwind.css";

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider defaultTheme="system" attribute="class">
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;

```

```jsx
// themeswitch.js
import { useState, useEffect } from "react";
import { useTheme } from "next-themes";

const ThemeSwitch = () => {
  const [mounted, setMounted] = useState(false);
  const { resolvedTheme, setTheme } = useTheme();
  console.log(resolvedTheme);
  // useEffect only runs on the client, so now we can safely show the UI
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  return (
    <select
      value={resolvedTheme}
      onChange={e => setTheme(e.target.value)}>
      <option value="system">System</option>
      <option value="dark">Dark</option>
      <option value="light">Light</option>
    </select>
  );
};

export default ThemeSwitch;
```

**Comment by pacocoursey** [comment]
The `resolvedTheme` is, well, resolved. It won't return `system`, but rather whatever theme `system` resolved to. [From the docs](https://github.com/pacocoursey/next-themes#usetheme-1):

> resolvedTheme: If enableSystem is true and the active theme is "system", this returns whether the system preference resolved to "dark" or "light". Otherwise, identical to theme
