### ISSUE TITLE
unable to change root or body background 

### ISSUE THREAD

**Issue by dellwatson** [pacocoursey/next-themes#117]
currently the theme is working but i cant change default root background

```js
body {
  /* Your default theme */
  background: #eee;
}
[data-theme='dark'],
[data-theme='dark'] body {
  color: #fff;
  background: #020202;
}

```
also I use tailwind, and i already setup as in documentation.
example will be given if this responded

when i remove ` attribute='class'` 
this css code seems to work 
```js
[data-theme='dark'],
[data-theme='dark'] body {
  color: #fff;
  background: #020202;
}
```
but i lost the benefit of updating in class, 
and even if i activate it, it's not working properly only work for `dark:blabla ` the `light:blabla` version is not working

**Comment by pacocoursey** [comment]
When the attribute is class, you need to use a class selector in your CSS, not the data attribute selector.

```
.dark, .dark body {
  …
}
```
