### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pacocoursey** [pacocoursey/next-themes#12]
We should use React Testing Library to setup tests for correct behavior, including:
- Using `attribute="class"`
- Using custom `storageKey`
- Using custom `value` mappings
- Using `attribute="data-something-other-than-theme"`
- Using different `defaultTheme`s

**Comment by trm217** [comment]
If no one is on this already, I'd be willing to give it a go once the PR for v0.0.13 is merged.

**Comment by pacocoursey** [comment]
That'd be great @trm217! I just published v0.0.13 🎉

**Comment by trm217** [comment]
I am busy until the end of next week. 
I'll start working on this after that. 
I'&ll keep you posted on the progress once I've started.

**Comment by trm217** [comment]
@pacocoursey I created a [draft-PR](https://github.com/pacocoursey/next-themes/pull/35), is there anything else you want tested?
