### ISSUE TITLE
React v18 types support

### ISSUE THREAD

**Issue by jonahsnider** [pacocoursey/next-themes#122]
React v18 had a breaking change to the `FC` type.
TypeScript users of this library now see an error like this one when trying to use the `ThemeProvider` component:

```sh
$ tsc --noEmit
src/pages/_app.tsx:47:3 - error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ThemeProviderProps'.

47  <ThemeProvider>
     ~~~~~~~~~~~~~


Found 1 error in src/pages/_app.tsx:47
```

The relevant source for `ThemeProvider` is here:
https://github.com/pacocoursey/next-themes/blob/a85bb62fa432a87659469c127fc464f8756a913c/src/index.tsx#L20

The same issue is likely present in any other public types which use `FC`.

---

There are 2 ways I might fix this:
1. Create a breaking release that requires the minimum React version to be v18. Use `FC<PropsWithChildren<T>>` instead of `FC<T>`
2. Replace all usage of `FC` with a type the library itself provides to avoid `FC` inconsistencies between React v18 and older versions

Happy to make a PR to make either of those changes, or a change you think is a better solution.

**Comment by pacocoursey** [comment]
Hi, which version of `next-themes` are you using? I cannot reproduce any type errors in Next.js projects using React 18 and up-to-date type packages.

`children` is manually typed here, not relied on `.FC` to provide it:

https://github.com/pacocoursey/next-themes/blob/a85bb62fa432a87659469c127fc464f8756a913c/src/types.ts#L42

**Comment by jonahsnider** [comment]
Ah, looks like I was using v0.0.13-beta.3 instead of a more recent version. Updating to v0.2.0 fixed the issue.

**Comment by osequi** [comment]
I'm using: 

```json
"next": "latest",
"next-themes": "^0.2.1",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

And getting:

```
Type error: 'Component' cannot be used as a JSX component.
  Its element type 'Component<any, any, any> | ReactElement<any, any>' is not a valid JSX element.
    Type 'Component<any, any, any>' is not assignable to type 'Element | ElementClass'.
      Type 'Component<any, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/cs/osequi/osequi/apps/osequi/node_modules/@types/react-dom/node_modules/@types/react/ts5.0/index").ReactNode'.
            Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
              Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.

  15 |     <main className={inter.className}>
  16 |       <ThemeProvider>
> 17 |         <Component {...pageProps} />
     |          ^
  18 |       </ThemeProvider>
  19 |     </main>
```

Thanks! :)
