### ISSUE TITLE
Is `mounted` the best way to solve the hydration mismatch?

### ISSUE THREAD

**Issue by TszHong0411** [pacocoursey/next-themes#124]
When I use the `mounted` way to solve the hydration mismatch problem, the search engine can't catch the mounted section.

I hope there are other ways to solve this because I think to keep adding 'mounted' is inconvenient.

![Snipaste_2022-06-22_18-48-23](https://user-images.githubusercontent.com/75498339/175012910-8bbde78b-9be7-4fb7-8f6c-de2f0a268c9d.png)

![Snipaste_2022-06-22_18-49-14](https://user-images.githubusercontent.com/75498339/175012926-c5f0c7d6-fa7d-465b-9d90-30cbe511d46d.png)
.

**Comment by pacocoursey** [comment]
You don’t have to wrap the _entire_ render method with mounted! Just your theme switcher part. In your case the `<Button>Set to ...</Button>` part.
