### ISSUE TITLE
When I add 'class' as an attribute to the theme provider I get this error. I use Nextjs with tailwindcss. Is there any hope for me?

### ISSUE THREAD

**Issue by AryanKuAg** [pacocoursey/next-themes#128]
![image](https://user-images.githubusercontent.com/61811630/180770209-2a0ba9f3-24f9-4560-ac60-d152e8126edb.png)
![image](https://user-images.githubusercontent.com/61811630/180770393-84e4460a-0785-4759-b808-3ed2dff1f8db.png)

If i remove the 'class' from the attribute then error gone.

**Comment by AryanKuAg** [comment]
![image](https://user-images.githubusercontent.com/61811630/180770587-51ca158b-4270-49ce-9821-6abd762411f8.png)
I want that bg-white will normally show white background and when i do dark:bg-black, then it will show me the activated dark mode. I configured all the things as mentioned in the docs, but nothing happened.   help!!!

**Comment by pacocoursey** [comment]
Does the base class name on your `html` element contain invalid characters? Sounds like the API is failing to modify the class name because the existing version is invalid? Need more info.

**Comment by AryanKuAg** [comment]
> 
![image](https://user-images.githubusercontent.com/61811630/181461530-5744ad6f-49ce-4f53-a72e-e6b92c772d14.png)

Its a Next.js Project, Idk where is the html file, though I don't modify anything on `html`  , I just add `class` as **attribute** and this throws an error that I mentioned above.

**Comment by pacocoursey** [comment]
Oh, weird. What browser are you using?

**Comment by AryanKuAg** [comment]
> Oh, weird. What browser are you using?

Thanks for taking interest in my problem. I'm using Brave, Chrome, Firefox and Tor.

**Comment by pacocoursey** [comment]
@AryanKuAg are you still seeing this issue? I really think it can only be a browser bug, or something deep inside your application code.

**Comment by ekqt** [comment]
@AryanKuAg Check out this small blog post: [No-brainer Dark Mode for Next.js](https://hectorsosa.me/blog/no-brainer-dark-mode-for-next.js-EPNTw). I'm also using Next plus TalwindCSS. Make sure you are following those steps. 

If you still come across this issue please let me know, I'd be happy to help.
