### ISSUE TITLE
Does not work on the server side

### ISSUE THREAD

**Issue by jjborrelli28** [pacocoursey/next-themes#132]
Hello!

I have an application built with Next.js, TypeScript and Stitches for the styles.

I installed next-themes for theme management but I have two problems.

1- It is not loading a value for theme on the server side, through TS I can see that it returns undefine on the server and string on the client.

2- To solve the above I have to configure a classic isMounted state to render the client-side app, but it still generates a flash effect (I have configured "dark" as the default theme).

Values returned by useTheme:
![Screen Shot 2022-07-27 at 18 55 13](https://user-images.githubusercontent.com/86693473/181380635-e89b87c4-d533-4544-824f-a71e2c9d9acf.png)

ThemeProvider Configuration:
![Screen Shot 2022-07-27 at 19 04 31](https://user-images.githubusercontent.com/86693473/181380646-fbce3a04-eb84-45c1-b9c6-3b2184743e6f.png)

I hope you can help me, thank you very much.

**Comment by pacocoursey** [comment]
https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

**Comment by jjborrelli28** [comment]
ty!
