### ISSUE TITLE
i tried to use this one Reactjs app instead of nextjs app. darkmode flashes if i refresh the page. how do it fix.

### ISSUE THREAD

**Issue by abdarker** [pacocoursey/next-themes#137]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/14371506/190239477-2f069e07-ad5d-41ec-96be-11d564148c60.png">
this script should run on <head> tag why it's running in root!.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/14371506/190239874-ebf15e8c-4601-48f3-b81d-92556f44db4d.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/14371506/190239949-2e214b14-9f0f-469b-8102-f1a3be67049f.png">
i tried wrapping themeprovider in index.js file too. same it flashes

**Comment by pacocoursey** [comment]
No guarantee this library works outside of Next.js. PRs welcome to support CRA, or maybe someone else can help you out here.
