### ISSUE TITLE
Nextjs Interpolation Error with dynamic routes

### ISSUE THREAD

**Issue by merthanmerter** [pacocoursey/next-themes#139]
When I change theme in a dynamic page I get Interpolation error. Couldn't find a solution in the documentation.
Thanks in advance.

`Error: The provided `href` (/products/[category]) value is missing query values (category) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed`

**Comment by pacocoursey** [comment]
Hey, this doesn't look like an error with this library, but rather a Next.js error. The error message shows you a link with more info and how to fix it: https://nextjs.org/docs/messages/href-interpolation-failed

**Comment by merthanmerter** [comment]
> Hey, this doesn't look like an error with this library, but rather a Next.js error. The error message shows you a link with more info and how to fix it: https://nextjs.org/docs/messages/href-interpolation-failed

Yes but it happens when I use the default setTheme hook

**Comment by merthanmerter** [comment]
Ok, so turns out it happens if I do that from layout.
