### ISSUE TITLE
Server / client mismatch

### ISSUE THREAD

**Issue by mondoadams** [pacocoursey/next-themes#14]
When using the `useTheme` hook I'm getting an error when trying to read the `theme` value. Using Next v10.

``` js
import { useTheme } from "next-themes"

export default function ThemeChanger() {
    const { theme, setTheme } = useTheme()

    return (
        <div>
	    <div>{theme}</div>
	    <button onClick={() => setTheme("light")}>Light Mode</button>
	    <button onClick={() => setTheme("dark")}>Dark Mode</button>
        </div>
    )
}
```

```Warning: Text content did not match. Server: "" Client: "dark"```

**Comment by pacocoursey** [comment]
This is expected, you should avoid rendering any theme-reliant UI until mounted on the client. I added [more documentation about this](https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch) to the README.
