### ISSUE TITLE
Started to flash in Production

### ISSUE THREAD

**Issue by ilyagru** [pacocoursey/next-themes#141]
# Hi!

It weirdly started to flash after I deployed to Production on Vercel but there is no flash on the preview environment. I'm not sure if some kind of configuration conflicts with the implementation or something else. 

Reproducible on https://ilyagru.com - flashes both when you open the website with dark mode enabled earlier or reload the page, in Safari and Firefox. But not reproducible in the preview https://ilyagru-next-git-post-deploy-fixes-ilyagru.vercel.app.

Any ideas what to check?

## My usage:
```tsx
<ThemeProvider attribute='class' enableSystem={false}>
  {getLayout(<Component {...pageProps} />)}
</ThemeProvider>
```

##  Versions 
```json
"next": "12.3.1",
"next-pwa": "^5.6.0",
"next-themes": "^0.2.1",
```

**Comment by B2o5T** [comment]
we discovered also flash in `0.2.1`, maybe it's related to `next export` because we use it

**Comment by B2o5T** [comment]
found why flash appears for us, more info here https://github.com/vercel/next.js/issues/41359

**Comment by balazsorban44** [comment]
@ilyagru is your repository public? I would like to have a look.

**Comment by ilyagru** [comment]
@balazsorban44 no, it's not public. Let me know where exactly you would like to take a look.

**Comment by andreacassani** [comment]
Hi, had the same issue, if you are using Cloudflare try disabling the various toggles under Speed > Optimization. Worked for me, still have to track which optimization was causing the issue.

**Comment by ilyagru** [comment]
@andreacassani wow, thank you! Yes, disabling Rocket Loader on Cloudflare has resolved this for me. Will close the issue for now.

**Comment by michaelroyzen** [comment]
Had this issue as well. Can confirm that disabling rocket loader worked.
