### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by sharmapukar217** [pacocoursey/next-themes#148]
I tried this with some other react framework and since this support all react framework, shouldn't the name be "react-themes" and also next is not used , i think that can be renoved from peer dependency 🤔

**Comment by pacocoursey** [comment]
This package was never intended to be used outside of Next.js. It's become generic enough for that to happen, but I haven't really considered it as a primary use case yet. Maybe in the future we can make it be `react-themes` and drop the `next` dep!

**Comment by sharmapukar217** [comment]
Sure then, I'm closing this issue as this issue was raised just to bring the maintainer's focus on this topic 😃
