### ISSUE TITLE
defaultTheme not working

### ISSUE THREAD

**Issue by glenames** [pacocoursey/next-themes#15]
Im seeing two (related) issues with the library. Most obvious is that the defaultTheme doesn't appear to work.

With a basic setup - system theme works great, but if I add the following, system theme is still active:

```
    <ThemeProvider defaultTheme="dark">
```

I attempted to disable system theme which did turn off system theme but light theme remained.

Further to the above - the repository example doesn't apply system theme when deployed to Vercel (although your demo does) - as can be seen in the public repository:

https://next-themes.vercel.app/

No default is set - but useTheme returns light instead of system.

**Comment by pacocoursey** [comment]
Hey @glenames, this is all expected. The default `defaultTheme` is "light", which you can see here:

https://github.com/pacocoursey/next-themes/blob/eaa4a0c78f0620104e3d73f84daff90b889fffbd/index.tsx#L47

And is also [mentioned in the README](https://github.com/pacocoursey/next-themes#themeprovider).

---

The `defaultTheme` is only used for new visitors to your site. As soon as they visit, the defaultTheme will be stored in `localStorage`, so if you change your ThemeProvider value of `defaultTheme` it won't matter, since `localStorage` will take priority after the first visit.

I can see how this behavior is a little weird – did you expect that the theme would only be stored in `localStorage` once they modified it to something other than the default?

**Comment by glenames** [comment]
Ok that does make sense and identified what I was doing wrong. The challenge was that once I had setup my app without a default - it wasn't obvious why it wasn't working. Id suggest a couple of changes to help understand this better:

- If the user isn't using setTheme (Just wants to use system theme default) - don't bother setting localStorage allowing fallback to default unless the user has actively changed the theme.
- In the example app use defaultTheme="system" 
- In the docs example (2 lines) also use defaultTheme="system" 

otherwise the statement "your Next.js app fully supports dark mode, including System preference with prefers-color-scheme" isn't strictly true - nothing has changed in your app based on these two lines, you still need to wire up the manual change thing. Though - if default theme was system - you do immediately have a theme which reacts to user preferred setting.

I suspect there are a number of people who want to use the library just to get a user preferred theme setup and these changes would make it clear how that works.

One additional note (Perhaps a separate issue, though i'm questioning my understanding) forcedTheme seems to be broken on v0.8 - it throws an error "Uncaught ReferenceError: d is not defined" (For "dark") This based on example.

**Comment by pacocoursey** [comment]
> One additional note (Perhaps a separate issue, though i'm questioning my understanding) forcedTheme seems to be broken on v0.8 - it throws an error "Uncaught ReferenceError: d is not defined" (For "dark") This based on example.

Thanks, fixed on v0.9!

---

- I agree with (1), and will remove updating `localStorage` until the user actually changes their preferred theme via `setTheme`.
 - I'll think more about making "system" be the automatic default. It seems like a good idea, but I'm wondering if it could have any negative side effects.

**Comment by glenames** [comment]
> * I'll think more about making "system" be the automatic default. It seems like a good idea, but I'm wondering if it could have any negative side effects.

My opinion is that it makes a lot of sense - people are adopting this library in large part for that and its easily disabled. Opting out is more clear than having to opt in.
