### ISSUE TITLE
useTheme make react hydration error in next.js 13 

### ISSUE THREAD

**Issue by confact** [pacocoursey/next-themes#153]
I am using resolvedTheme in next.js to check what theme is used to switch images. I have not change anything and it works in next.js 12, when migrating to next.js 13 it create react hydration error: https://nextjs.org/docs/messages/react-hydration-error

The code I use is:
```
import { useTheme } from 'next-themes'
export function PrimaryFeatures() {
  const { resolvedTheme } = useTheme()
  ...
}
```
When commenting out useTheme() line and just do `const resolvedTheme = 'dark'` it works.

What could the problem be? is it really a bug? no one else got this issue, it seems like.

**Comment by ehsanbigzad** [comment]
A I created a temporary solution with below approach and it works.

```ts
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

export default function useToggleTheme() {
  const { theme, setTheme } = useTheme();
  const [themeValue, setThemeValue] = useState<string>();

  useEffect(() => setThemeValue(theme), [theme]);

  return { theme: themeValue, setTheme };
}
```
To to used:
```ts
const { theme, setTheme } = useToggleTheme();
```

This [repository](https://github.com/ehsanbigzad/my-portfolio) may help you

**Comment by pacocoursey** [comment]
Merging into #152 for all Next.js 13 support
