### ISSUE TITLE
ThemeProvider get hydration issue with nextjs 13

### ISSUE THREAD

**Issue by Dulajdeshan** [pacocoursey/next-themes#155]
I am using `next-themes` with nextjs 13. I have wrapped my component with` <ThemeProvider>`. It's getting hydration issue.

**ISSUE**

![image](https://user-images.githubusercontent.com/38158937/203571218-ff138c24-fdc5-446a-851c-761fbd59361a.png)

**_app.tsx**

![image](https://user-images.githubusercontent.com/38158937/203571449-c37a1e82-3785-4040-96bb-baa968b02d74.png)

**Versions**
`"react": "18.2.0"`
`"next": "13.0.4"`
`"next-themes": "^0.2.1"`

**Comment by pacocoursey** [comment]
Merging into #152 for all Next.js 13 support
