### ISSUE TITLE
attribute="class" causing the following error with Tailwindcss and nextjs

### ISSUE THREAD

**Issue by avastamin** [pacocoursey/next-themes#157]
It's working only with `ThemeProvider` but not working with `attribute="class"`
```
  <ThemeProvider attribute="class">
      <Component {...pageProps} />
    </ThemeProvider>
```

InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('[object Object]') contains HTML space characters, which are not valid in tokens.

**Comment by martingoodloans** [comment]
I only noticed this happening when providing a function to the `setTheme` function.

e.g

```
setTheme((prev) => prev === 'dark' ? 'light' : 'dark')
```

This sets the function as a string to LocalStorage. Not sure if you're seeing the issue for this reason.

**Comment by 684efs3** [comment]
I got this while working in NextJs 13

**Comment by brentrobbins** [comment]
@684efs3 How were you able to get this working in Nextjs version 13? Are you using the App directory?

**Comment by EtanHey** [comment]
same problem here
using appDir

**Comment by prince272** [comment]
same problem too
using appDir

**Comment by mormeni** [comment]
Please, I will like to know if someone found a work around on this issue.

**Comment by TheBusix** [comment]
Hey, has anyone here got an update about this issue? I am using Next.js 13 with appdir, thanks in advance!

**Comment by boldrack** [comment]
This issue still persists for both nextjs13 and 14 . anyone got it working yet ?

**Comment by steezplusplus** [comment]
> 1. In Chrome Developer Tools, go to Application > Local Storage > delete the `theme` variable

This worked for me.

**Comment by pacocoursey** [comment]
Fixed in latest versions.
