### ISSUE TITLE
Why have `next` as peer dependency

### ISSUE THREAD

**Issue by B2o5T** [pacocoursey/next-themes#159]
Any reason to have `next` as peer deps ?
https://github.com/pacocoursey/next-themes/blob/8fc17e2a53aeb9e5918f8b9152795e56712ea862/package.json#L20

I think `next-themes` can be React framework agnostic since `next-themes` doesn't use `next` somewhere 🤔.

**Comment by ronildo** [comment]
Any update on this? I would love to use it in my project, but it's not a Next project.

**Comment by RIP21** [comment]
> Any update on this? I would love to use it in my project, but it's not a Next project.

Just use it. Patch peerDependencies and that's about it.

Package is pretty simple, so you can always fork :)
