### ISSUE TITLE
Flashing on Firefox still continues

### ISSUE THREAD

**Issue by DenizUgur** [pacocoursey/next-themes#162]
Same issue as #85. It's quite inconsistent though. The same page hosted on github.com does this flickering but not on netlify.com. Even on localhost there are some times it doesn't do this but can't say how much (it's too infrequent).

Edit: It appears to be a problem with only github.com and localhost when viewed on Firefox. It works on netlify regardless of which browser I try. If there aren't any other cases of this I'd be more than happy to help in any way that I can.

**Comment by ErAz7** [comment]
Looks related to [this fix](https://github.com/pacocoursey/next-themes/pull/163)
you can test on [the fork](https://github.com/ErAz7/next-themes/tree/fix-flash-when-mapping-value)

**Comment by DenizUgur** [comment]
I found the problem. Dark Reader extension is causing this. Even though it's disabled inside extension settings it affects the page. When I disabled the extension from browser the problem went away.

**Comment by ErAz7** [comment]
okay then
however, currently using value mapping causes flashing on both dev and prod
