### ISSUE TITLE
Flashing Google Chrome

### ISSUE THREAD

**Issue by colaquecez** [pacocoursey/next-themes#165]
Hey, I'm having a flashing problem only when I use google chrome; in the video, I switched to safari, and as you can see, the problem doesn't happen.

I've tested using a chrome private tab and don't see the flashing.

"next": "^13.1.2",
 "next-themes": "^0.2.1",

https://user-images.githubusercontent.com/38195454/214970404-5fa16deb-d4e8-47aa-9f1e-78391e59d43e.mov

![Screenshot 2023-01-26 at 7 58 27 PM](https://user-images.githubusercontent.com/38195454/214969560-29ad621a-c463-4844-9da6-b99f1c92812e.png)

**Comment by trm217** [comment]
We require more context to help you out with this issue.
For one, what styling-lib are you using if any? How does your styling factor in dark-mode?
Is all of that able to be gathered while rendering on the server (where the user-preference is not available in most-cases), or is the dark-mode style only loaded once react has rehydrated on the client.

**Comment by colaquecez** [comment]
Hey @trm217, I'm using the styled-components, but I'm not using its provider, all of it is gathered while rendering on the server

![Screenshot 2023-01-30 at 5 57 35 PM](https://user-images.githubusercontent.com/38195454/215593309-4efa8862-8535-477b-a3e7-97b7efa18080.png)

**Comment by trm217** [comment]
In that case, please share a minimal-reproduction. Can't really help from what I've got.

**Comment by trm217** [comment]
Feel free to provide a repo and I will try to help you out with your setup issues if it still persists.
