### ISSUE TITLE
next js 13 required use client at the top to wrok as client component

### ISSUE THREAD

**Issue by viveksinra** [pacocoursey/next-themes#166]
for page 
next-themes/dist/index.js
need to Add the "use client" directive at the top of the file to use it.

otherwise i am getting "TypeError: createContext only works in Client Components." 

![image](https://user-images.githubusercontent.com/37905082/218269234-be0d8658-a558-4936-8074-1336b53e7924.png)

**Comment by captainkidd5** [comment]
what was the solution here?
