### ISSUE TITLE
Cookie Strategy

### ISSUE THREAD

**Issue by kesne** [pacocoursey/next-themes#17]
I was performance testing a website using `next-themes` and I noticed that it seemed to delay the first paint a little bit. Would you be open to using a cookie-based strategy that would allow for reading the user-set theme directly on the server-side rather than having to define a script tag that is inserted into the head of the document?

**Comment by pacocoursey** [comment]
Have you noticed it causing a significant delay? In my tests, the blocking head script takes about 2-3ms of execution time. With localStorage you pay the price of a small blocking script, but the benefit is pretty big.

I think that cookies are objectively worse:
- Forces your pages to be SSR, which alone causes more performance issues than a 2-3ms script does
- Does not support SSG pages
- You will still need a blocking script to support System theme (for full support at least)
- Cookie parsing/setting is more verbose than localStorage, likely requiring a 5kb+ library

People have attempted a Cookie solution before ([see Julia's demo](https://github.com/juliaqiuxy/theming-demo/tree/master/src/lib)) but it always seems to fall short.

**Comment by pacocoursey** [comment]
Closing since, as described above, I don't think this is a good idea. Feel free to ping me and I'll re-open if there's something more to consider.

**Comment by nazarposhta** [comment]
I faced a problem with this plugin, when had to implement dark mode on main and sub domains. In case with cookies (as an option) and possibility to pass a domain parameter, the problem with sub domains wold be solved.

**Comment by FINDarkside** [comment]
I don't really see the drawbacks of cookies. For example I don't think "Forces your pages to be SSR" is correct. The benefit of cookies is that it enables you to do SSR. Any code that needs to access theme value cannot be rendered on server side right now because the server doesn't know the theme.

**Comment by pacocoursey** [comment]
I guess it would be cookies _and_ inline script, not _or_. Cookies could be a valid storage strategy (alongside `localStorage` and `sessionStorage`) but we'd still require the blocking inline script, which is what this issue was about.

**Comment by minjunkyeong** [comment]
To avoid hydration errors, the example returns null until it is mounted, so the benefit of seo over SSR is lost.

https://github.com/pacocoursey/next-themes#:~:text=Avoid%20Hydration%20Mismatch

```js
import { useState, useEffect } from 'react'
import { useTheme } from 'next-themes'

const ThemeSwitch = () => {
  const [mounted, setMounted] = useState(false)
  const { theme, setTheme } = useTheme()

  // useEffect only runs on the client, so now we can safely show the UI
  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return null
  }

  return (
    <select value={theme} onChange={e => setTheme(e.target.value)}>
      <option value="system">System</option>
      <option value="dark">Dark</option>
      <option value="light">Light</option>
    </select>
  )
}

export default ThemeSwitch
```


So, if you have to worry about seo, isn't it appropriate to use this library that uses local storage?
