### ISSUE TITLE
useTheme Hook is causing re-renders

### ISSUE THREAD

**Issue by MrUltimate** [pacocoursey/next-themes#182]
Hello there,

I'm trying to make a switcher with `framer-motion` that animates on mount. Using the example, I am using `resolvedTheme` from the `useTheme()` to set my toggle. Unfortunately this seems like the `useTheme()` hook runs on every page navigation, therefore causing a re-render on every page navigation (thereby also triggering the framer-motion animations).

Is there anyway to prevent this behavior?

```javascript
<ThemeToggle onClick={handleThemeSwitch}>
    {mounted && resolvedTheme === 'dark' ? (
      <>
        <Light /> Light mode
      </>
    ) : (
      <>
        <Dark /> Dark mode
      </>
    )}
</ThemeToggle>
```

**Comment by therawk** [comment]
Seeing this has been open for almost 3 months:
Have you found a solution for this issue?

**Comment by MrUltimate** [comment]
> Seeing this has been open for almost 3 months: Have you found a solution for this issue?

Yes, I moved my `<Header />` out of the my layout component and into my `_app.js`. This was Next doesn't re-render persistent elements.
