### ISSUE TITLE
inline styles based on theme

### ISSUE THREAD

**Issue by FuuKowatty** [pacocoursey/next-themes#185]
I want to move my div based on chosen theme but receive that error

Warning: Prop `className` did not match. Server: "w-[18px] h-[18px] bg-lightBlue rounded-full absolute\n          right-[2px]" Client: "w-[18px] h-[18px] bg-lightBlue rounded-full absolute\n          left-[2px]"
div
div
DarkModeToggle@webpack-internal:///(app-client)/./src/components/DarkModeButton.tsx:12:88

      <div
        className={`w-[18px] h-[18px] bg-lightBlue rounded-full absolute
          ${theme == "dark" ? 'left-[2px]' : 'right-[2px]'}`}
      />

**Comment by pacocoursey** [comment]
Use Tailwind's dark selector instead:

```tsx
dark:left-[2px] dark:right-0 right-[2px]
```

You should read the docs about hydration mismatch: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

**Comment by FuuKowatty** [comment]
Thank you very much!
