### ISSUE TITLE
Hydration errors/warnings after multiple themes

### ISSUE THREAD

**Issue by ttsoares** [pacocoursey/next-themes#190]
NextJS 13.4.8, Next-themes 0.2.1, Tailwind 3.3.2.
Just with that configs for dark/light as is in the documentation:  fine.
But if one tries multiple custom themes the Hydration issue appears...  
Tried all available solutions, for example like those here:
[https://www.youtube.com/watch?v=RTAJ-enfums](https://www.youtube.com/watch?v=RTAJ-enfums)
Even placing 'use client' in all files...
One example of what I'm trying:
[https://github.com/pacocoursey/next-themes/issues/189](https://github.com/pacocoursey/next-themes/issues/189)

**Comment by pacocoursey** [comment]
We'd need a more specific example to help you here, but you should probably read the documentation about avoiding hydration mismatch: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

Additionally, you should be adding `suppressHydrationWarning` on the `ThemeProvider` when using the /app directory.

**Comment by ttsoares** [comment]
Tried all suggestions so far... No avail.
[thematicalculator.tar.zip](https://github.com/pacocoursey/next-themes/files/12062203/thematicalculator.tar.zip)
Example attached.
