### ISSUE TITLE
Is it really Next.js only?

### ISSUE THREAD

**Issue by RIP21** [pacocoursey/next-themes#191]
Looking at the code it looks like it should work just fine with any other framework/SPA. Anything in the implementation that is really fine-tuned to the Next? As far as I can see it would work just fine in Vite and whatnot.

Will be glad to hear a confirmation of that :)

**Comment by RIP21** [comment]
Works in Vite SPA just fine ¯\_(ツ)_/¯

Highly recommend :D

**Comment by B2o5T** [comment]
@RIP21 duplicate https://github.com/pacocoursey/next-themes/issues/159

If you confirmed that it works in `vite`, you’ll still have peerdependency warning about missing `next` dependency

**Comment by RIP21** [comment]
> @RIP21 duplicate https://github.com/pacocoursey/next-themes/issues/159
> 
> If you confirmed that it works in `vite`, you’ll still have peerdependency warning about missing `next` dependency

Yup, correct. I used .pnpmfile.cjs file to patch that. Other than that, works just fine.

**Comment by B2o5T** [comment]
You can patch with out of box pnpm patches https://pnpm.io/cli/patch

**Comment by Mingyang-Li** [comment]
I'm a bit late to the party... I can confirm `next-themes` works fine in React Vite app.
