### ISSUE TITLE
useTheme returns undefined in next js 

### ISSUE THREAD

**Issue by KOFI-GYIMAH** [pacocoursey/next-themes#193]
when used in a component (with the exception of components in the pages dir), useTheme returns undefined even id 'use client'; is specified in the component.
Thus: the navbar component where useTheme is being used to toggle dark <-> light mode is imported and used in a page component, when the toggle button is clicked, useTheme returns undefined but returns a light/dark value when useTheme is used in a page component itself

**Comment by pacocoursey** [comment]
https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

**Comment by chiragksharma** [comment]
in my case I defined the _app.tsx instead of _app.js 
renaming it worked for me
