### ISSUE TITLE
Calling SetTheme doesn't immediately update the background-color

### ISSUE THREAD

**Issue by smithshelke** [pacocoursey/next-themes#206]
Im trying to update `theme-color` meta tags after calling `setTheme`. However when i log the css `background-color`, it is still the older one. 
for ex.
```
useEffect(() => {
  const bgColor =  getComputedStyle(document.body).getPropertyValue('background-color')
  console.log(bgColor) //white
},[theme])
setTheme('dark')
```
However when i do the same log from chrome developer console after i do `setTheme('dark')`, i get black.

So im assuming that this is some race condition. A solution could be to have a callback after the theme is set and the css classes are updated.

**Comment by pacocoursey** [comment]
You could use the new `flushSync()` React function to ensure that your `setTheme` call has finished before reading the new values.

We apply the theme updates in a `useEffect` inside the library itself, so the order may not be guaranteed.
