### ISSUE TITLE
Next13 - undefined theme on useTheme

### ISSUE THREAD

**Issue by M4RC0Sx** [pacocoursey/next-themes#216]
Hi there, I have my Next13 app set up with this providers on the main layout:
![imagen](https://github.com/pacocoursey/next-themes/assets/43318927/126aa171-7053-4a17-8935-e8aa93f26939)
![imagen](https://github.com/pacocoursey/next-themes/assets/43318927/5b3cc2d7-c01c-46c4-a7c1-39b1040f459e)

Then, I have a theme switcher component:
![imagen](https://github.com/pacocoursey/next-themes/assets/43318927/4752ca4a-2bfe-4e6f-bb00-d04326bfb9ac)

I think all is client-sided and configured following all guides. But when I click the theme switcher, theme property is undefined and theme is not changing. (All the console.log properties from above are undefined).

I don't know what is happening, the theme is being added in the class:
![imagen](https://github.com/pacocoursey/next-themes/assets/43318927/69a12cd8-8cf2-4ad6-882b-d6d014b73a50)

Any suggestions?
My versions are:
![imagen](https://github.com/pacocoursey/next-themes/assets/43318927/dcf681b2-88d3-468d-85af-0a0812597f7d)

**Comment by M4RC0Sx** [comment]
I have found that if don't place my ThemeSwitcher component inside the NavBar component and instead I place it directly in the page.tsx, it works. Why is that?

**Comment by M4RC0Sx** [comment]
Issue solved. I wasn't placing the ThemeSwitcher inside the provider. Sorry!

**Comment by chiragksharma** [comment]
Thanks a lot this helped, was stuck for hours on this.
also you can use the `ThemeProvider` directly from the next-themes
