### ISSUE TITLE
How to pass `nonce` to `ThemeProvider` in `_app.tsx`?

### ISSUE THREAD

**Issue by rikusen0335** [pacocoursey/next-themes#218]
Due to Next.js's regular csp setting, we are generating `nonce` in `_document.tsx` and need to pass it to `_app.tsx`

Below code is just example I am using tho doesn't work, getting two of errors:
`Warning: Extra attributes from the server: nonce script` when passing nonce through `nonce` to `App` like `nonce={nonce}`
`Warning: Prop 'nonce' did not match. Server: "" Client: "sOmEtHiNgHaShGeNeRaTeD=="` when passing nonce through `pageProps.nonce`

```tsx
// _document.tsx code
const MyDocument = () => {
  const csp = `...`

  return (
    <Html lang="ja">
      <Head nonce={nonce}>
        <meta httpEquiv="Content-Security-Policy" content={csp} />
      </Head>
      <body>
        <Main />
        <NextScript nonce={nonce} />
      </body>
    </Html>
  )
}

MyDocument.getInitialProps = async (ctx: DocumentContext) => {
  const nonce = generateNonce()

  const originalRenderPage = ctx.renderPage
  ctx.renderPage = () =>
    originalRenderPage({
      enhanceApp: (App: React.ComponentType<React.ComponentProps<AppType> & { nonce: string }>) =>
        function EnhancedApp(props) {
          props.pageProps.nonce = nonce // pageProps.nonce or nonce only either one is needed
          return <App nonce={nonce} {...props} />
        }
    })

  const initialProps = await Document.getInitialProps(ctx)

  return {
    ...initialProps,
    nonce
  }
}

export default MyDocument
// end of _document.tsx


// _app.tsx code
export const MyApp = ({
  Component,
  pageProps,
  nonce
}: NextAppProps) => {
  <ThemeProvider nonce={nonce}>
    <Component {...pageProps} />
  </ThemeProvider>
}

export default MyApp
// end of _app.tsx
```

**Comment by rikusen0335** [comment]
Additional info: As a workaround, I put hash of all the scripts inside <head> tag including next-themes's, so that we can add hash to nonce like `sha256-abcdefghijk...` to permit scripts.

**Comment by Enalmada** [comment]
@rikusen0335 I think this is the fix: https://github.com/pacocoursey/next-themes/pull/223

I created  "@enalmada/next-themes": "^0.2.3" as a workaround.

**Comment by r34son** [comment]
Everything works with 0.3.0, but the error still persists in console. Maybe it's related to this comment https://github.com/vercel/next.js/discussions/54907#discussioncomment-8545524.

@pacocoursey  NextJs Script implementation also doesn't apply nonce on client, due to this comment https://github.com/vercel/next.js/blob/v14.2.0-canary.48/packages/next/src/client/script.tsx#L228.

Related https://github.com/facebook/react/issues/26028
