### ISSUE TITLE
Question: How does next-themes resolve "No flash on load"?

### ISSUE THREAD

**Issue by kimizuy** [pacocoursey/next-themes#23]
Or what part of the code do I need to read?
I want to figure this out on my own.
Let me know if you want to.

**Comment by kimizuy** [comment]
I found hints about this problem.

https://github.com/gaearon/overreacted.io/blob/master/src/html.js#L21

https://hangindev.com/blog/avoid-flash-of-default-theme-an-implementation-of-dark-mode-in-react-app

**Comment by pacocoursey** [comment]
Hey, the [source code is public right here in this repo](https://github.com/pacocoursey/next-themes/blob/e56cd4a5a15411036b74e10954fb1969866b2e18/index.tsx#L208-L231) 😄 Both of the links you shared are pretty good. My version is minified to decrease HTML size and has some tricks to speed up execution, but generally the idea is the same: include a render-blocking inline script that determines the theme.

**Comment by kimizuy** [comment]
Thanks! I try it!
