### ISSUE TITLE
How can I get a transition between dark and light mode

### ISSUE THREAD

**Issue by dearfrankg** [pacocoursey/next-themes#239]
I would like the dark mode to fade to light mode and visa versa.

I tried adding this CSS 

```css
html {
  @apply transition-colors ease-in-out duration-700;
}
```

After adding that CSS my header text will delay the color changes, but the bg-color change happens instantly.

**Comment by PixeledCode** [comment]
A reproducible on Codesandbox might help. Does using `transition-all` help?

**Comment by dearfrankg** [comment]
> A reproducible on Codesandbox might help. Just to test, does using `transition-all` help?

Did not help

**Comment by modyabhi** [comment]
Been trying to figure this out aswell for the last few days, same issue here. On refresh its scuffed aswell.

**Comment by mohiwalla** [comment]
Did you guyz find any solution yet?

**Comment by pacocoursey** [comment]
This is not related to the library.

**Comment by pyyding** [comment]
Something like this works

```
function toggleTheme() {
    document.startViewTransition(() => {
      setTheme(theme === 'dark' ? 'light' : 'dark');
    });
  }
```
