### ISSUE TITLE
Inconsistent theming when the page loads

### ISSUE THREAD

**Issue by Sachinv220** [pacocoursey/next-themes#243]
I want to invert the colours of an image when the theme is light, this is the code.
```javascript
export function DarkImage({ ...props }: ImageProps) {
  const { theme } = useTheme();

  if (theme === "dark") {
    return <Image {...props} className="filter invert" />;
  } else {
    return <Image {...props} />;
  }
}
```
but when the page loads there is inconsistent, but when I toggle theme it works fine. Is there a problem with next-theme or Nextjs 14.

**Comment by Sachinv220** [comment]
This is the [https://github.com/Sachinv220/chat/tree/ui](repo) the changes are present only in the ui branch.

the files that would be related to the current issue
`src/components/Logo.tsx`
`src/app/page.tsx`
`src/app/layout.tsx`

**Comment by PixeledCode** [comment]
Could be related to [Hydration Mismtach](https://github.com/pacocoursey/next-themes/tree/main#avoid-hydration-mismatch)
Also there is higher chance of getting help if you create a reproducible on CodeSandBox

**Comment by Sachinv220** [comment]
here is the link to the [CodeSandBox](https://codesandbox.io/p/github/Sachinv220/chat/ui?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq7x7c5g01eb3b6eax93hx9c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq7x7c5g01e53b6e2gk2f6ji%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq7x7c5g01e83b6ekkoq7iv0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq7x7c5g01ea3b6ef0gnjbdl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq7x7c5g01e53b6e2gk2f6ji%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7x7c5f01e43b6eywcg94pv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clq7x7c5g01e53b6e2gk2f6ji%2522%252C%2522activeTabId%2522%253A%2522clq7x7c5f01e43b6eywcg94pv%2522%257D%252C%2522clq7x7c5g01ea3b6ef0gnjbdl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7x7c5g01e93b6ee6gq1b9w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq7x7c5g01ea3b6ef0gnjbdl%2522%252C%2522activeTabId%2522%253A%2522clq7x7c5g01e93b6ee6gq1b9w%2522%257D%252C%2522clq7x7c5g01e83b6ekkoq7iv0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7x7c5g01e63b6er8wobw4v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clq7x7c5g01e73b6e3nv8mqmy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq7x3n23002geghh1rkn70bu%2522%257D%255D%252C%2522id%2522%253A%2522clq7x7c5g01e83b6ekkoq7iv0%2522%252C%2522activeTabId%2522%253A%2522clq7x7c5g01e63b6er8wobw4v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Sachinv220** [comment]
Thank You,I will take a look.
