### ISSUE TITLE
Documentation out of date with Tailwind's new dark-mode API

### ISSUE THREAD

**Issue by MichaelAllenWarner** [pacocoursey/next-themes#250]
Tailwind [recently changed](https://github.com/tailwindlabs/tailwindcss/pull/12717) their dark-mode API:

- The default "media" strategy remains unchanged.
- The "class" strategy (mentioned in the `next-themes` README) still exists for backward-compatibility, and under the hood it still does `` addVariant('dark', `:is(${selector} &)`) ``.
- The new "selector" strategy is meant to replace the "class" strategy going forward. It behaves similarly, but it has reduced specificity and is a little more flexible: `` addVariant('dark', `&:where(${selector}, ${selector} *)`) ``.
- The new "variant" strategy allows for total customization of the `dark:` variant: `addVariant('dark', selector)`. 

The new strategies aren't yet documented on the Tailwind website, but they were shipped in v. 3.4.1. (A slightly different version shipped in 3.4.0, but it had problems.)

The README for this repository should probably be updated accordingly.

**Comment by joshuawootonn** [comment]
You could just ... update the README.md?

Might just update it if I figure it out 👿

**Comment by joshuawootonn** [comment]
I missed this before but looks like someone already has a proposal for the README.md update. 

Here is [the commit](https://github.com/joshuawootonn/type-the-word/commit/aa7a4110aa6939dc5cb9832edb4edb3ddea6b25d) I used to move from the `media` strategy to the `selector` strategy with this library if this can help anyone.

**Comment by joshuawootonn** [comment]
Fair enough. I was in a spicy late night mood. Probably wouldn't have posted normally. It just felt like an easy change. Thanks for contributing the update though. Hope it get's merged soon!

**Comment by renchris** [comment]
I also had to include a `localStorage.theme` value for this to work. Would we be able to add this to the documentation as well?

```ts
// On page load or when changing themes, best to add inline in `head` to avoid FOUC
document.documentElement.classList.toggle(
  'dark',
  localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)
)

// Whenever the user explicitly chooses light mode
localStorage.theme = 'light'

// Whenever the user explicitly chooses dark mode
localStorage.theme = 'dark'

// Whenever the user explicitly chooses to respect the OS preference
localStorage.removeItem('theme')
```

[Supporting system preference and manual selection](https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection)
