### ISSUE TITLE
Warning: Text content did not match. Server: "sun" Client: "moon"

### ISSUE THREAD

**Issue by benfiratkaya** [pacocoursey/next-themes#27]
My code working well but I see a warning in console.
>Warning: Text content did not match. Server: "sun" Client: "moon"
```javascript
import { useTheme } from "next-themes";

const ThemeSwitcher = () => {
  const { theme, setTheme } = useTheme();

  const themeIcon = theme === "light" ? "moon" : "sun"; // because of this code
  const changeTheme = () => {
    return theme === "light" ? setTheme("dark") : setTheme("light");
  };
  return (
    <div onClick={changeTheme}>
      {themeIcon}
    </div>
  );
};

export default ThemeSwitcher;

```

How can I fix this?

**Comment by andrewbrey** [comment]
@benfiratkaya I suspect that you're issue is what's mentioned in the README about hydration mismatch: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch.

**Comment by benfiratkaya** [comment]
Thanks!

**Comment by alex-drocks** [comment]
> @benfiratkaya I suspect that your issue is what's mentioned in the README about hydration mismatch: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch.

Confirmed. I had the same problem and the readme example fixed it. Thanks.
