### ISSUE TITLE
next-themes fail during installation.

### ISSUE THREAD

**Issue by elnobun** [pacocoursey/next-themes#28]
When I run `npm install next-themes`, I am getting this error:

```
npm ERR! Found: next@10.0.7
npm ERR! node_modules/next
npm ERR!   next@"10.0.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9.5.5" from next-themes@0.0.10
npm ERR! node_modules/next-themes
npm ERR!   next-themes@"0.0.10" from the root project
```

Please advice. Thanks.

**Comment by sarthaktexas** [comment]
If you read the entire thing it says to use `--force` at the end of the command. @pacocoursey should fix this but he's doing cool things at @vercel I presume.

**Comment by pacocoursey** [comment]
I'm not able to reproduce this issue. I changed the way peer deps are specified so it shouldn't be locked to a specific version anymore. Please try again and let me know if this is still happening!

**Comment by sarthaktexas** [comment]
YAY :tada:! It worked! Thanks a lot @pacocoursey!

**Comment by elnobun** [comment]
@pacocoursey , Thanks for fixing this issue. Thanks for the effort.

@sarthaktexas, thanks. Although using `--force` works, it also has its quirks. That was what I tried in the first place before reporting this issue. I don't want to be using `--force` to install packages in a production application. But I am glad that it's resolved now. 😊 I will be closing this issue.
