### ISSUE TITLE
Theme flashing v0.3.0

### ISSUE THREAD

**Issue by andrew-arkhipov** [pacocoursey/next-themes#281]
Exact same issue as in #85 is being seen on v0.3.0. Users have complained that changing from dark mode to light mode causes rapid flashing between the two (as seen in the video above), and the only fix is closing the browser. Sometimes it also occurs randomly - the user doesn't click or interact with anything and all of a sudden the theme starts flashing back and forth. Most of the reports are coming from users who are using the new Arc browser, so perhaps there's some conflict between next-themes' and Arc's implementations.

I haven't been able to reproduce locally, but please see #85 to understand what it looks like. I'm using the `resolvedTheme` variable to determine which theme to show.

Usage below:

```
const MyApp: NextComponentType<AppContext, AppInitialProps, AppLayoutProps> = ({
  Component,
  pageProps,
}: AppLayoutProps) => {
  return (
    <ThemeProvider enableSystem={false} attribute="class" disableTransitionOnChange>
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
```

**Comment by andrew-arkhipov** [comment]
https://github.com/pacocoursey/next-themes/assets/44785877/095821cf-647e-482e-ae44-c43a8e00f521

@pacocoursey here's a reproduction. Any ideas on what this can be? Thank you!

**Comment by peteretelej** [comment]
are you using a custom ThemeProvider component that wraps the next-themes ThemeProvider in a `"use client"` client side component? This was a previous workaround that's no longer needed on v.0.3.0, if you still have it I suspect it's causing this.

You can directly `import { ThemeProvider } from "next-themes";` directly in your main layout

**Comment by andrew-arkhipov** [comment]
> are you using a custom ThemeProvider component that wraps the next-themes ThemeProvider in a `"use client"` client side component? This was a previous workaround that's no longer needed on v.0.3.0, if you still have it I suspect it's causing this.
> 
> You can directly `import { ThemeProvider } from "next-themes";` directly in your main layout

@peteretelej I am not, but thanks for the suggestion. For reference, here's my implementation:

```
import '@/styles/globals.css'
import '@radix-ui/themes/styles.css'

import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import type { NextComponentType } from 'next'
import { AppContext, AppInitialProps, AppLayoutProps } from 'next/app'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import { ThemeProvider } from 'next-themes'
import { AuthProvider } from '@propelauth/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import RouteProgressBar from '@/components/common/RouteProgressBar'
import { AUTH_URL } from '@/constants/env'
import { withAuth } from '@/helpers/auth'

const DynamicSidebar = dynamic(() => import(`@/components/common/Sidebar`), {
  ssr: false,
})
const DynamicToast = dynamic(() => import('@/components/common/Toast'), {
  ssr: false,
})

const inter = Inter({ subsets: ['latin'] })
const queryClient = new QueryClient()

const MyApp: NextComponentType<AppContext, AppInitialProps, AppLayoutProps> = ({
  Component,
  pageProps,
}: AppLayoutProps) => {
  const AuthComponent = withAuth(Component)
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <ThemeProvider attribute="class" disableTransitionOnChange>
        <AuthProvider authUrl={AUTH_URL}>
          <QueryClientProvider client={queryClient}>
            <Theme className={inter.className}>
              <RouteProgressBar />
              <AuthComponent {...pageProps} />
              <DynamicSidebar />
              <DynamicToast />
            </Theme>
          </QueryClientProvider>
        </AuthProvider>
      </ThemeProvider>
    </>
  )
}

export default MyApp
```

**Comment by lodado** [comment]
Are you using the CSP option? It worked when I turned off the options.

**Comment by andrew-arkhipov** [comment]
> Are you using the Content Security Policy (CSP) option? It worked when I turned off the options.

@lodado I’m not sure if I am, but that seems like something that’s only configurable by a given user at the browser level, and if this is happening for multiple users, it doesn’t seem like an actual fix. Thanks for the suggestion, though, and please correct me if I’m misunderstanding!

**Comment by patelvivekdev** [comment]
I am experiencing a similar issue with Next Themes. When I deploy my project to production and enable dark mode, the page initially loads in light mode before switching to dark mode after a hard refresh.


https://github.com/pacocoursey/next-themes/assets/43227010/48c898b2-c60a-427e-8a1c-8713f5d131e3

I have provided the following links for reference:
Link to my website: https://patelvivek.dev/
Repository link: https://github.com/patelvivekdev/patelvivek.dev

Additional information:
I am using Next.js Canary with Partial Page Rendering (PPR) enabled.

I would greatly appreciate any assistance in resolving this issue.

**Comment by thomasfw** [comment]
I'm getting the same seizure inducing flashing (in safari), using the implementation described in the docs.

**Comment by RobPruzan** [comment]
Getting the infinite screen flash on arc. I get this consistently across projects when using next-themes

**Comment by johannsonic** [comment]
Same here, getting the flash of a lifetime there

**Comment by jlarmstrongiv** [comment]
I found this issue commonly occurs when the website is open in more than one tab

**Comment by andrew-arkhipov** [comment]
> I found this issue commonly occurs when the website is open in more than one tab

Really interesting observation. Perhaps using session storage instead of local storage could help then?

**Comment by imMatheus** [comment]
I had the same issue, downgrading from `0.3.0` to `0.2.1` fixed it for me 🙏

**Comment by recursively** [comment]
Rapid flashing between light and dark themes occurs in all kinds of browsers including Chrome, safari, and edge. When multiple tabs are opened, this bug will be 100% reproduced.

**Comment by jamesryan-dev** [comment]
> I am experiencing a similar issue with Next Themes. When I deploy my project to production and enable dark mode, the page initially loads in light mode before switching to dark mode after a hard refresh.
> 
>  patelvivek.dev.mp4 
> I have provided the following links for reference: Link to my website: https://patelvivek.dev/ Repository link: https://github.com/patelvivekdev/patelvivek.dev
> 
> Additional information: I am using Next.js Canary with Partial Page Rendering (PPR) enabled.
> 
> I would greatly appreciate any assistance in resolving this issue.

unrelated

**Comment by patelvivekdev** [comment]
> > I am experiencing a similar issue with Next Themes. When I deploy my project to production and enable dark mode, the page initially loads in light mode before switching to dark mode after a hard refresh.
> > patelvivek.dev.mp4
> > I have provided the following links for reference: Link to my website: https://patelvivek.dev/ Repository link: https://github.com/patelvivekdev/patelvivek.dev
> > Additional information: I am using Next.js Canary with Partial Page Rendering (PPR) enabled.
> > I would greatly appreciate any assistance in resolving this issue.
> 
> unrelated

For me, this was causing the issue https://github.com/pacocoursey/next-themes/pull/156

 I've temporarily disabled Rocket Loader on Cloudflare.

**Comment by jlarmstrongiv** [comment]
I run into this issue without Rocket Loader

**Comment by mambucodev** [comment]
> I run into this issue without Rocket Loader

For the moment diasbling Rocket Loader has fixed it for me. I'll let you guys know if the issue comes back again.

**Comment by pacocoursey** [comment]
All of these reports sound like Rocket Loader Cloudflare issues. Please refer to the docs about that: https://github.com/pacocoursey/next-themes#using-with-cloudflare-rocket-loader

**Comment by andrew-arkhipov** [comment]
@pacocoursey I do not use Cloudflare for my deployment, nor does @jlarmstrongiv, as mentioned above, so I don't think this issue can be closed. Thanks for your understanding.
