### ISSUE TITLE
[Bug]: Wrong type of parameter received in setTheme callback 

### ISSUE THREAD

**Issue by PranavDhamanage** [pacocoursey/next-themes#305]
### What happened?

While providing a callback to the `setTheme` function returned from the hook `useTheme`, the callback receives the parameter which is basically the prevState which is of type `function` rather than a `string`. But in typescript it shows that we can only receive the parameter of type `string` but in reality it's a `function` or a `string`. In ideal scenario it should be only `string`.
<img width="635" alt="image" src="https://github.com/pacocoursey/next-themes/assets/59444220/9b87fd95-d666-4607-99e0-9811c24647db">
<img width="559" alt="image" src="https://github.com/pacocoursey/next-themes/assets/59444220/3cc2b7c1-592e-40ab-b554-1f67794ff9fe">

Please let me know if there is any missing understanding from my side 😄  Thanks in advance 👍 

### Version

0.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by ryanagillie** [comment]
This issue was fixed in https://github.com/pacocoursey/next-themes/pull/286 but they haven't done a release for it, @pacocoursey any idea why?

**Comment by pacocoursey** [comment]
Hey, this should be fixed in the latest versions.
