### ISSUE TITLE
[Feature request]: using two providers in the same project

### ISSUE THREAD

**Issue by balajiudayagiri** [pacocoursey/next-themes#307]
### What feature would you like to see?

I'm working on a Next.js application where I want to manage themes with two different providers at different levels in the project hierarchy. Here's the structure I have in mind:

```
src
|--app (home route) has its provider
|    |--dark theme route has its separate state that manages its theme
```

In this setup, the home route has a global theme provider defined at its root level. However, I need to add a separate theme provider for a specific route with a custom layout. This route should have its theme state and a different key in local storage, making its theme independent of the global theme.

How can I achieve this, or is there a feature that could help me implement this?

**Comment by balajiudayagiri** [comment]
i found a solution

**Comment by fernandezremi** [comment]
Hey! What’s the solution you implemented? Can you tell us more about it? 😉

**Comment by balajiudayagiri** [comment]
Hey @fernandezremi! 👋

I managed to get multiple themes working by creating a dynamic `ThemeProvider` that switches themes based on the route. Here's a brief overview of how I set it up:

```tsx
"use client";

import React, { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { ThemeProvider } from "next-themes";
import { ThemeProviderProps } from "next-themes/dist/types";

interface ProvidersProps extends ThemeProviderProps {
  children: React.ReactNode;
}

/**
 * Providers component to manage theme based on the route.
 *
 * @param {ProvidersProps} props - The props for the component.
 * @param {React.ReactNode} props.children - The children components to be rendered within the ThemeProvider.
 * @param {object} props - Additional props to be spread onto the ThemeProvider.
 * @returns {JSX.Element} The ThemeProvider component with conditional theming based on the route.
 */
export const NextThemesProviders: React.FC<ProvidersProps> = ({
  children,
  ...rest
}) => {
  const pathname = usePathname();
  const [theme, setTheme] = useState<string | undefined>(undefined);

  // Define custom themes for specific routes
  const themeRoutes: { [key: string]: string } = {
    home: "violet-theme",
    about: "blue-theme",
    work: "blue-theme",
    contact: "green-theme",
  };

  useEffect(() => {
    // Get the first segment of the pathname (e.g., 'blogs' from '/blogs/post')
    const firstPathSegment = pathname.split("/").filter(Boolean)[0];

    // Set theme based on route or fallback to default (global theme)
    const themeFromPathname = themeRoutes[firstPathSegment] || undefined;
    setTheme(themeFromPathname);
  }, [pathname]);

  return (
    <ThemeProvider
      forcedTheme={theme} // Apply route-specific theme if defined
      attribute="class"
      defaultTheme="dark"
      themes={["light", "dark", "blue-theme", "violet-theme", "green-theme"]}
      enableSystem={false}
      disableTransitionOnChange
      {...rest}
    >
      {children}
    </ThemeProvider>
  );
};
```

### How It Works:
- I created an internal logic that assigns the theme based on the path segment, avoiding directly exposing the route names.
- Using `usePathname`, I check the current route’s first segment and set the appropriate theme using `setTheme`.
- The global theme (default `dark`) is applied everywhere else.
- Themes are set dynamically based on the path, without disclosing the specific route names in the code.

This keeps the implementation clean and allows for flexibility, while hiding the routes and managing theme states independently.

Let me know if you have any questions! 😊

---

Hope that helps! 🚀
