### ISSUE TITLE
[Bug]: defaultTheme not work when it is differrent from localstorage theme

### ISSUE THREAD

**Issue by shyfang** [pacocoursey/next-themes#312]
### What happened?

Which one has higher priority, localStorage or defaultTheme? When theme===dark in localstorage and defaultTheme====light, defaultTheme does not take effect
I need to get the custom theme from the query 
first, I change the theme dark, then the localStorage theme is dark
second, https:xxx.com/?theme=light, I get the theme from query, then 
` <ThemeProvider defaultTheme={query.theme}>xxx</ThemeProvider>`
defaultTheme not work 

### Version

0.3.0
### What browsers are you seeing the problem on?

Chrome

**Comment by joseph0926** [comment]
https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/src/script.ts#L41

---
localstorage seems to have a higher priority

**Comment by pacocoursey** [comment]
Obviously the theme in `localStorage` takes precedence. The `defaultTheme` is just that, a `defaultTheme` for when another theme is not available.
