### ISSUE TITLE
[Bug]: Next.JS 15 - Hydration Failed: -className="dark" -style={{color-scheme:"dark"}}

### ISSUE THREAD

**Issue by AChangXD** [pacocoursey/next-themes#316]
### What happened?

After upgrading to Next.JS 15, I am now encountering a Hydration error. This error was not there in Next.JS 15 or the 15 RC version that I was using.
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/5cdfe705-a5d8-4f67-bf1d-ec2aeefe8eac">

Adding a mounted check for `<NextThemesProvider/>` removes the hydration error but introduces another error: 

<img width="973" alt="image" src="https://github.com/user-attachments/assets/402cdb30-f3b3-446a-9c62-49039fd460b4">

### Version

0.3.0

### What browsers are you seeing the problem on?

Safari

**Comment by fab-uleuh** [comment]
Same issue with Next 15

**Comment by devmoatassem** [comment]
I'm also experiencing the same issue with Next.js 15

**Comment by uigywnkiub** [comment]
Currently next upgrades to 15.0.1 by default and it's canary, so this bug also catches me.
<img width="767" alt="image" src="https://github.com/user-attachments/assets/08eab6c9-a6f7-474d-a6eb-c14fa1329c83">

**Comment by jonathanwilke** [comment]
Same for me on Next.js 15.0.0 stable

**Comment by jonathanwilke** [comment]
This can not be the solution as it will not work on SSR and will cause the UI to flash when dark mode is selected

**Comment by Goldziher** [comment]
This works for me:

```tsx
export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" className="dark" style={{ "color-scheme": "dark" } as CSSProperties}>
			<body>...</body>
		</html>
	);
}
```

Theme toggling also works. 

For a better experience, shift the detection of color theme preference from CSS to a theme selector component or another use client component called in the root layout. Example:

```tsx
"use client";

import { MoonIcon, SunIcon } from "@radix-ui/react-icons";
import { Button } from "gen/ui/button";
import { useTheme } from "next-themes";
import { useEffect } from "react";

export function ThemeToggle() {
	const { setTheme, theme } = useTheme();

	useEffect(() => {
		const isDarkTheme = globalThis.matchMedia('(prefers-color-scheme: dark)').matches

		setTheme(isDarkTheme ? "dark" : "light");
		}, []);

	return (
		<Button
			data-testid="theme-toggle-button"
			variant="ghost"
			className="dark:hover:bg-primary/20"
			onClick={() => {
				setTheme(theme === "light" ? "dark" : "light");
			}}
		>
			<SunIcon data-testid="theme-toggle-sun-icon" className="dark:hidden h-6 w-6" />
			<MoonIcon data-testid="theme-toggle-moon-icon" className="hidden dark:block bg-inherit h-6 w-6" />
			<span data-testid="theme-toggle-sr-text" className="sr-only">
				Toggle theme
			</span>
		</Button>
	);
}
```

**Comment by MiniOcean404** [comment]
Me too

**Comment by Milind-Jamnekar** [comment]
For now I added `suppressHydrationWarning` in my `html` tag as suggested by[ nextjs doc](https://nextjs.org/docs/messages/react-hydration-error#solution-3-using-suppresshydrationwarning) until next-theme come up with any fix. this is how you would use in your `layout.tsx`

```
<html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
    </body>
</html>
```

**Comment by gfargo** [comment]
Another solution is to wrap your `<ThemeProvider>` with a `<Suspense>`, [mentioned here](https://github.com/pacocoursey/next-themes/issues/318#issuecomment-2442033101), e.g.

```
 <Suspense fallback={<div>Loading...</div>}>
    <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
      {children}
    </ThemeProvider>
  </Suspense>
  ```
  
  Resolves the error/warning for me without having to add `suppressHydrationWarning` 💭

**Comment by maxwiseman** [comment]
@Goldziher By adding `className="dark" style={{ "colorScheme": "dark" }}`, you're effectively just suppressing the error. This resolves the error because it happens to match the result of the operations that are run by `ThemeProvider`. You'll see the error again if you switch your device to light mode.

Also not really sure how adding another client component changes anything. Seems like your component pretty much does what `ThemeProvider` does already (see below).
https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/src/index.tsx#L42-L79 https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/src/index.tsx#L135-L138

**Comment by maxwiseman** [comment]
> I'm using tailwind, so I did `className="dark"` on my `<html/>` tag. For now, the black to white flash for light mode is 100% better than the white to black flash in dark mode. Would love a fix for this

@AChangXD You created that white flash. NextJS pre-renders client components, but when it does that, it doesn't run `useState` or `useEffect`. Therefor, when your `ThemeProvider` gets pre-rendered, Next will use the default `mounted` value (false), and render `<></>`. Next is pre-rendering a blank document which gets hydrated into your app on the client, so until that hydration happens, you're seeing the blank document, which is white by default. As mentioned by @jonathanwilke, this also effectively disables SSR and SSG for your **entire app**. next-theme will solve this flash if you let it, but by preventing it from rendering at first, you aren't allowing it to. 

The hydration error is expected. There won't be a "fix" for it. It's even [mentioned in the readme](https://github.com/pacocoursey/next-themes/tree/main#:~:text=Note!%20If%20you%20do%20not%20add%20suppressHydrationWarning%20to%20your%20%3Chtml%3E%20you%20will%20get%20warnings%20because%20next%2Dthemes%20updates%20that%20element.%20This%20property%20only%20applies%20one%20level%20deep%2C%20so%20it%20won%27t%20block%20hydration%20warnings%20on%20other%20elements.). For whatever reason Next hasn't really been showing the error until now, but the behavior is the same as its always been.

**The correct solution is to suppress the hydration warning.**

**Comment by pacocoursey** [comment]
Please read the docs: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app

**Comment by SanketPathare** [comment]
> Currently next upgrades to 15.0.1 by default and it's canary, so this bug also catches me. <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/29861553/378752476-08eab6c9-a6f7-474d-a6eb-c14fa1329c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MzI4MTEsIm5iZiI6MTczNzUzMjUxMSwicGF0aCI6Ii8yOTg2MTU1My8zNzg3NTI0NzYtMDhlYWI2YzktYTZmNy00NzRkLWE2ZWItYzE0ZmExMzI5YzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDA3NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTc1Yjc1ZTM3ZjQwYTBlOGFkNTRmYzk2MWNhYjk2NDg0OTNmYTE1MjI1NTU4YTI4YWNiMDJlMmUyMWE4N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PNxSiLkc1SJOw70GMtnnKijF52ajyJi8lnVV4aUUzys">



> ### What happened?
> After upgrading to Next.JS 15, I am now encountering a Hydration error. This error was not there in Next.JS 15 or the 15 RC version that I was using. <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/51896236/378664557-5cdfe705-a5d8-4f67-bf1d-ec2aeefe8eac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1NDc5MzMsIm5iZiI6MTczNzU0NzYzMywicGF0aCI6Ii81MTg5NjIzNi8zNzg2NjQ1NTctNWNkZmU3MDUtYTVkOC00ZjY3LWJmMWQtZWMyYWVlZmU4ZWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDEyMDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDdmYzAxNGU1NmQyMGE1MWJhZTYxMWZkODRjMDA3ODZlNGUzMWJlMGMxZmMxZjFiMWYwNGE1ODA1MWM3NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p3MVKe0iTor9fSKR5xWc2myhbSZZsqz1fhETgUPIpuQ">
> 
> Adding a mounted check for `<NextThemesProvider/>` removes the hydration error but introduces another error:
> 
> <img alt="image" width="973" src="https://private-user-images.githubusercontent.com/51896236/378665953-402cdb30-f3b3-446a-9c62-49039fd460b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1NDc5MzMsIm5iZiI6MTczNzU0NzYzMywicGF0aCI6Ii81MTg5NjIzNi8zNzg2NjU5NTMtNDAyY2RiMzAtZjNiMy00NDZhLTljNjItNDkwMzlmZDQ2MGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDEyMDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNmNiY2RiNWI2NjQ4ZmFmZGQyMmY5ODdkNjU2YmE3MWI0NmEzYTFhZWFhZjVhZGUwN2JmN2Q1NTg4ZDZkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0J6I9HvcoImv3ynrCal-ncK8ymN5GWkkFCA1xkqo4e8">
> ### Version
> 0.3.0
> 
> ### What browsers are you seeing the problem on?
> Safari

Problem solution :

```
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTheme from "@/Components/NextTheme";
import Navbar from "@/Components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <NextTheme>
            <Navbar />
            {children}
          </NextTheme>
        </body>
      </html>
    </ClerkProvider>
  );
}


``` 
Add in layout html  attribute  -  "suppressHydrationWarning "
