### ISSUE TITLE
[Bug]: Deletion of the ThemeProviderProps

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [pacocoursey/next-themes#322]
### What happened?

Because I'm using RSC, I abstracted the ThemeProvider into its own component. I used the `ThemeProviderProps` from `next-themes/dist/types` to make Typescript happy and type the props this component is accepting to pass them down to the `ThemeProvider`. Unfortunately, with the update to 0.4, I can't find these props anymore. I would request that they be brought back.

### Version

0.4.0 and higher

**Comment by DEBargha2004** [comment]
Hey You can use this
`React.ComponentProps<typeof NextThemesProvider>`
This will work

**Comment by sotsugov** [comment]
Alternatively, you can bring the props down to the provider, if that's an option:

```
'use client';

import { ThemeProvider as NextThemesProvider } from 'next-themes';

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  return (
    <NextThemesProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      {children}
    </NextThemesProvider>
  );
}

```

**Comment by matthewspear** [comment]
I couldn't seem to get @DEBargha2004 to work as ComponentProps needed an arg... So filled in the value using `typeof`:

```typescript
"use client";

import * as React from "react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { type ComponentProps } from "react";

export function ThemeProvider({
  children,
  ...props
}: ComponentProps<typeof NextThemesProvider>) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
```

Seems to work for me!

**Comment by pacocoursey** [comment]
Sorry about that, types are now exported again in `0.4.2`

**Comment by SugarDarius** [comment]
Thank you @pacocoursey 🙏🏻

**Comment by JamesSingleton** [comment]
Looks like they are exported from `next-themes` instead of from `import { type ThemeProviderProps } from 'next-themes/dist/types'` for anyone curious. Importing from `next-themes/dist/types` gives me `Cannot find module 'next-themes/dist/types' or its corresponding type declarations.`. However, doing

```
import { ThemeProvider, type ThemeProviderProps } from 'next-themes'
```

Seems to work just fine
