### ISSUE TITLE
[Bug]: Theme flashing

### ISSUE THREAD

**Issue by andrew-arkhipov** [pacocoursey/next-themes#323]
### What happened?

Reopening #281 since I do not use Cloudflare but am still experiencing this.

Exact same issue as in #85 is being seen on v0.3.0. Users have complained that changing from dark mode to light mode causes rapid flashing between the two (as seen in the video above), and the only fix is closing the browser. Sometimes it also occurs randomly - the user doesn't click or interact with anything and all of a sudden the theme starts flashing back and forth. 

Usage below:

```
const MyApp: NextComponentType<AppContext, AppInitialProps, AppLayoutProps> = ({
  Component,
  pageProps,
}: AppLayoutProps) => {
  return (
    <ThemeProvider enableSystem={false} attribute="class" disableTransitionOnChange>
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
```

### Version

0.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by andrew-arkhipov** [comment]
https://github.com/user-attachments/assets/f42d065c-8d40-42d6-b6c0-c63e05a58c50

**Comment by pacocoursey** [comment]
Looks like you have `useEffect` code that is setting the theme in a loop. Can you share your application code that probably contains the bug?

**Comment by andrew-arkhipov** [comment]
Thanks for the response! Here's the only place in my codebase that sets the theme. `DropdownMenuItem` (and similar) is from Radix/Shadcn.

```
 <DropdownMenuSubContent className="w-36">
    {THEME_OPTIONS.map((option) => {
      const icon =
        THEME_ICON_MAP[option.value as keyof typeof THEME_ICON_MAP]
      return (
        <DropdownMenuItem
          key={option.value}
          onClick={() => setTheme(option.value)}
          className="h-7"
        >
          <div className="flex items-center justify-between w-full">
            <div className="flex items-center gap-x-2">
              {icon}
              {option.name}
            </div>
            {theme === option.value && (
              <HiMiniCheck className="w-[14px] h-[14px] text-primary-900 dark:text-primary-200" />
            )}
          </div>
        </DropdownMenuItem>
      )
    })}
  </DropdownMenuSubContent>
  ```

**Comment by pacocoursey** [comment]
Hmm that all looks okay. When the infinite loop occurs, could you open the "Source" tab in Chrome dev tools and pause execution to see what exactly is happening? Also happy to debug if you have a deployed version I can take a look at.

**Comment by andrew-arkhipov** [comment]
Unfortunately, this occurs completely randomly, though I have noticed that the rate of occurrence seems to be higher when I have a million tabs open on Chrome (random tabs + multiple instances of my app, maybe that's a clue to you?). Next time it occurs, I'll take a look as you described and post my findings in this issue.

I don't have a public version for you to look at right now, unfortunately, but really appreciate your willingness to take a look.

Thanks so much for your help and time!

**Comment by pacocoursey** [comment]
Multiple tabs does seem to be a clue, I saw that was reported in the other issues as well. I wonder if `storage` events are triggering other `storage` events, causing a loop.

**Comment by MArtytraM99** [comment]
+1 on the issue

I can't reproduce it reliably but it happens only on Safari. Chrome and Brave seem to be fine.

**Comment by thomasfw** [comment]
+1 

- Not using Cloudflare
- Using Safari

**Comment by MArtytraM99** [comment]
It only happens sometimes on friend's MacBook in only in Safari and only on deployed production build when opened in multiple tabs. We could not figure out the reproducibility conditions but we realised that change in one tab will affect other tabs instantly. We did not found any major websites that react to changes in other tabs instantly.

I cannot share my repository and I cannot reproduce the issue on my machine. I can share parts of the codebase if you would specify what do you need.

**Comment by leandrolavore** [comment]
any luck with this? I am having the same issue, on a Next 13 app. Just migrated to Chakra v3 and this issue comes up pretty consistently on Chrome by just having a few tabs open and switching color mode back and forth three or four times.

**Comment by Wekananda** [comment]
+1

- Using Chrome

**Comment by wcjohnson** [comment]
I am encountering this issue as well. Regrettably, I don't have an easy reproduction case. However, I can provide some pieces of information that might be helpful:

- The flashing happens as an eventual side effect of invoking the `setTheme` function returned by `useTheme`.
- In my code, this is tied to clicking a theme-toggle button. I have confirmed my code is only calling `setTheme` once per click. The effect is not being driven by a degenerate loop in my code etc.
- Sometimes it takes two to three clicks of the button to get the flashing to begin.
- The flashing only happens when I run under `next dev`.
- When I build and deploy with `next build`, the flashing does not reproduce and the button works as expected.

Hopefully this is helpful.
