### ISSUE TITLE
[Bug]: Next 15 support 

### ISSUE THREAD

**Issue by tongchen92** [pacocoursey/next-themes#324]
### What happened?

<img width="945" alt="Screenshot 2024-11-06 at 12 45 24 AM" src="https://github.com/user-attachments/assets/4b80b828-f057-44dc-9546-d0544551536e">
Seems like there's some hydration issue when using next theme with next 15

### Version

0.4.3

**Comment by ununununium** [comment]
+1

**Comment by Yousuf-95** [comment]
+1

**Comment by danihengeveld** [comment]
+1

**Comment by aabuhijleh** [comment]
According to [the docs](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app), when using the app router, you should add `suppressHydrationWarning` to `html` element in `layout.tsx` 

This fixed the problem for me.

**Comment by pacocoursey** [comment]
Please read the docs: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
