### ISSUE TITLE
@import based on theme?

### ISSUE THREAD

**Issue by gabriel-visualthinking** [pacocoursey/next-themes#43]
I have two themes in seperate stylesheets, and I was wondering if it's possible to import them based on the current theme. So it would import the dark.css if it's set to dark theme, or light.css if it's set to light theme.

**Comment by gabriel-visualthinking** [comment]
To clarify, the themes were not created by me, I am using PrimeReact and it's respective themes. These themes unfortunately have all colors hard coded, so I can't just flip variables to get the desired result...

**Comment by pacocoursey** [comment]
If all of the CSS is not loaded upfront, your page will flash depending on the theme. If you only load `light.css` but the page is in dark mode, you will have to load up `dark.css` lazily, which is too late.

If you're okay with it, you can do this by reading the current theme and updating your import based on it:

```js
const { theme } = useTheme()

return (
  <link rel="stylesheet" href={theme === 'light' ? 'light.css' : 'dark.css'}>
)

```
