### ISSUE TITLE
How to use next-themes with design libraries?

### ISSUE THREAD

**Issue by C0ntroller** [pacocoursey/next-themes#44]
In my latest project I used Ant Design as component framework and design library. But I still struggle to implement a dark mode switch in my NextJS app.
Ant Design provides a dark mode and a compact mode by itself (in CSS and LESS) but as far as I can tell you would have to modify these files to use next-themes to toggle between those designs.

Is there any better way to implement a theme switch but editing the provides style/creating a new one?

**Comment by trm217** [comment]
Could you elaborate your problem?

**Comment by C0ntroller** [comment]
So originally I wanted a way to toggle between to stylesheets because most design frameworks bring their own. But as I learned more about React, NextJS and your project I understood better how it works.

For me this was an issue with especifically Ant Design but should also apply to other Design Frameworks. 
antd provides three different stylesheets you can use - light, dark and compact.
I wanted to implement a switch that toggles between light and dark.

I solved it for now by using an extra .scss file with the following three lines:
```scss
@import "../../node_modules/antd/dist/antd";

[data-theme='dark'] {
  @import "../../node_modules/antd/dist/antd.dark";
}
```

As I don't believe there will a be a simpler workaround without NextJS changing their (S)CSS-only-in-top-level design choice I think this issue can be closed for now.

**Comment by trm217** [comment]
I am suprised to see that seperat stylesheet are being used in AntDesigns! Ever since CSS-variables were introduced, I have never seen separate stylesheets being used to handle different themes, since working with variable color palettes in most case is more than sufficient.
But yeah the problem you habe with loading different stylesheets is not what this library is made for. It's core purpose is to set theme identifiers (css-classes or attributes on the document element).

**Comment by C0ntroller** [comment]
Well ok it's only half the story. Because antd normaly uses less and the dark-theme-less only updates the color variables. But they also provide compiled css files which don't have any color variables anymore. 

As less is not trivial to install and setup especially if you have no experience with webpack I wanted to use the S/CSS because it's already built into NextJS. I bet you can write a quite simular file for a less stylesheet.

**Comment by pacocoursey** [comment]
> As I don't believe there will a be a simpler workaround without NextJS changing their (S)CSS-only-in-top-level design choice I think this issue can be closed for now.

Okay. I'm not sure there's anything next-themes can do here to improve on the integration with design libraries – they need to sort out a better way to do static CSS.
