### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by huysh3** [pacocoursey/next-themes#46]
Our legal team requires us to use packages after they review the license.
Grateful if you can add something like that~

**Comment by trm217** [comment]
Inside the package.json the license MIT is defined, is that not sufficient?

**Comment by huysh3** [comment]
Thanks for your response!

The package.json license define seems like cannot be recognized by this API:
https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository

I think MIT in package.json should be work for our condition, appreciate your awesome module!

**Comment by trm217** [comment]
It's actually @pacocoursey's library :)
Makes sense, if you check the doc of the endpoint you see that it returns the content of the file located at ./license, which in the case of this repo does not exist.

**Comment by pacocoursey** [comment]
Yep, the `license` field in `package.json` is pretty standard for this. I can add a separate license file but for your purposes it's safe to assume it's MIT :)
