### ISSUE TITLE
Theme switch not working if started from a forced theme page

### ISSUE THREAD

**Issue by putrikarunia** [pacocoursey/next-themes#47]
Hi, loving this library! Just found a bug here and wondering if there's a fix!

**Problem**
When started from a forced theme page, and then navigated back to a normal page, the dark/light switch doesn't work

**Steps to Reproduce**
1. In a new tab to https://next-themes-example.vercel.app/dark
2. Press "Go back home"
3. Switch from Light to Dark mode -> this doesn't work

Tested on Chrome/MacOS and Firefox/MacOS

https://user-images.githubusercontent.com/20483939/121750972-32d1ab80-cac2-11eb-9e41-01e05589bbd5.mov

Thank you!!

**Comment by pacocoursey** [comment]
Hey, this issue was fixed in 0.0.14 and I just didn't re-deploy the site. https://next-themes-example.vercel.app/ now works properly, thanks for the report!
