### ISSUE TITLE
`resolvedTheme` always returns `undefined`. `theme` does the same.

### ISSUE THREAD

**Issue by deadcoder0904** [pacocoursey/next-themes#49]
I was trying out `next-themes` for the last couple of weeks. I had a Mac then & I got it to work. Suddenly, it stopped working.

I thought `@mdx-js/loader` was the issue so I switched to `mdx-bundler`. Now on my Windows PC, it still returns `undefined`.

Idk what's the issue? Looks like everything I'm doing is right as per the docs.

I have made a complete repro that doesn't work https://github.com/deadcoder0904/mdx-bundler-next-themes-error

I have added `ThemeProvider`:

https://github.com/deadcoder0904/mdx-bundler-next-themes-error/blob/6c430e99caf932b2c96064449d3a3711df023ee8/src/pages/_app.tsx#L23-L25

And toggle the themes perfectly:

https://github.com/deadcoder0904/mdx-bundler-next-themes-error/blob/6c430e99caf932b2c96064449d3a3711df023ee8/src/components/DarkMode.tsx#L17

Yet I still get the `undefined` error. Is there something I am doing wrong?

**Comment by pacocoursey** [comment]
Hey, your Nav component is outside of the ThemeProvider, so it can't read any of the values.

Move this line down by 1:

https://github.com/deadcoder0904/mdx-bundler-next-themes-error/blob/6c430e99caf932b2c96064449d3a3711df023ee8/src/pages/_app.tsx#L22

---

I'll look into throwing a warning in dev mode if you `useTheme` outside of the context provider.

**Comment by deadcoder0904** [comment]
That has to be the most stupidest thing I've done. Rebuilt the whole project as well 😂 

Thanks for the quick fix :)
