### ISSUE TITLE
White border around messenger's customer chat icon on dark mode after reload a website

### ISSUE THREAD

**Issue by bubuq3** [pacocoursey/next-themes#52]
Hello, I got a dark mode from next/themes and on dark mode on my smartphone there is a white border of the messenger's icon (react-messenger-customer-chat). When I enter the website, change the theme to dark and then again enter the website there is white border around messenger's the icon and white bubble for the notifications. How to apply a color to this `iframe` and bubble for notifications? It doesn't look good ;/.  I use tailwindcss and next.js.

![image](https://user-images.githubusercontent.com/62507500/121919628-7bde6580-cd37-11eb-8f5c-e24e47527269.png)

I tried like this but dont work.:
```
@layer components {
  .cms-content > h1,
  h2 {
    @apply dark:text-gray-600;
  }
  .messenger-chat-bubble > iframe {
    @apply dark:bg-dark-posts;
  }
}
```
app.js

```
import "tailwindcss/tailwind.css";
import "../styles/globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { getMDXComponent } from "mdx-bundler/client";
import MessengerCustomerChat from "react-messenger-customer-chat";

import { ThemeProvider } from "next-themes";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <ThemeProvider attribute="class">
        <Header />
        <Component {...pageProps} />

        <Footer />
        {typeof window !== "undefiend" && (
          <MessengerCustomerChat
            pageId="1xxxxx"
            appId="xxx"
            className="messenger-chat-bubble"
          />
        )}
      </ThemeProvider>
    </>
  );
}
export default MyApp;
```
After entering the website, changing the theme to dark and reload the page
![200619910_970589787109373_1985134886635526940_n](https://user-images.githubusercontent.com/62507500/121926244-0e820300-cd3e-11eb-86fb-9488b8c276b4.jpg)

I tried this but didn't help
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .cms-content > h1,
  h2 {
    @apply dark:text-gray-600;
  }
  .messenger-chat-bubble > iframe {
    @apply dark:bg-dark-posts;
  }
  .messenger-chat-bubble > .fb_customer_chat_icon {
    @apply dark:bg-dark-posts;
  }
}
```

**Comment by pacocoursey** [comment]
This looks more like a request for CSS help than an issue with next-themes, please seek advice elsewhere

**Comment by Pavelkovo** [comment]
@bubuq3 
try to use enableColorScheme={false} in ThemeProvider
