### ISSUE TITLE
Incorrect behavior when using Paypal buttons

### ISSUE THREAD

**Issue by Pavelkovo** [pacocoursey/next-themes#64]
## Expected Behavior

The background of the component should be transparent.
Paypal uses an iframe to display the buttons.
I guess that's the problem. The library doesn't work with iframe correctly.

## Current Behavior

The background of the component is white. Regardless of which theme is selected or the which theme is forced.
<img width="437" alt="Screenshot 2021-11-01 at 23 34 34" src="https://user-images.githubusercontent.com/37384673/139738452-530325bc-a5d8-4ec4-8409-43436a9e3aeb.png">

## Steps to Reproduce

1. Next JS Project
2. Implement pay-pal buttons
3. Implement next-themes package
3. Load a page

## Your Environment

| Syntax      | Description |
| ----------- | ----------- |
| React | 17      |
| Next-themes    | 0.0.15        |
| Next.js   | 11        |
| Paypal sdk   | 4.1.0        |
| Browser   | 93.0.4577.82 (Official Build) (x86_64) |

**Comment by PavelTonkovichCeladonsoft** [comment]
I think it's related with:
[https://github.com/pacocoursey/next-themes/issues/52](url)

**Comment by Pavelkovo** [comment]
I think it's related with:
[https://github.com/pacocoursey/next-themes/issues/52](url)

**Comment by pacocoursey** [comment]
You can't generally change the styling of an iframe, because you don't own that nested document. You should check if it supports a theming API so you can modify the styles based on the theme.

**Comment by Pavelkovo** [comment]
Yeah) I know about that. Thanks for the feedback
