### ISSUE TITLE
Use <Script beforeInteractive /> instead of next/head for no flash injection?

### ISSUE THREAD

**Issue by cpakken** [pacocoursey/next-themes#66]
To my understanding next/head (not to be confused with {Head} from 'next/document') loads during client runtime as it allows users to dynamically update <title> etc...

I think Nextjs's Script tab with the beforeInteractive prop set is more suitable for this use-case
https://nextjs.org/docs/basic-features/script

> beforeInteractive
> Scripts that load with the beforeInteractive strategy are injected into the initial HTML from the server and run before self-bundled JavaScript is executed. This strategy should be used for any critical scripts that need to be fetched and executed before the page is interactive.
>

**Comment by pacocoursey** [comment]
Definitely something we can switch to now 👍 At the time of Next.js 11 release the `next/script` component was broken and `beforeInteractive` did not work correctly.

**Comment by pacocoursey** [comment]
Closing in favor of #84
