### ISSUE TITLE
TypeScript issue with ComponentType

### ISSUE THREAD

**Issue by pmarsceill** [pacocoursey/next-themes#68]
next-themes works great, but curious how to resolve this type issue in `_app.tsx`

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/896475/146656422-25127c85-b00b-4a45-a93f-afeb74b1a942.png">

**Comment by pacocoursey** [comment]
You can extend the NextPage type. Documentation here: https://nextjs.org/docs/basic-features/layouts

```ts
import type { NextPage } from 'next'

export default function App({ Component, pageProps }: { Component: NextPage & { theme?: string }) {

```

**Comment by pmarsceill** [comment]
Thank you!
