### ISSUE TITLE
Set color-scheme: dark in html style attribute with active custom theme

### ISSUE THREAD

**Issue by brootle** [pacocoursey/next-themes#77]
This is actually the result I want to get. I have multiple themes with my UI and some themes are designed for dark mode.  When I set up light or dark, no problem. But the question is how do I make my theme be dark 😀

This is what I want to get
`<html data-theme="cake" style="color-scheme: dark;">`

And this is what I currently have switching themes 
`<html data-theme="cake" style="">`

I feel like I probably miss something obvious?

**Comment by pacocoursey** [comment]
Right now `color-scheme` is only set when you use themes explicitly titled `dark` or `light`. There's no way to indicate that your custom theme "cake" is actually dark.

However this should be okay, because you can set it yourself in CSS.

```css
/* Wherever your theme CSS is... */
[data-theme="cake"] {
  color-scheme: dark;
}
```

**Comment by brootle** [comment]
thanks! nice trick!👍
