### ISSUE TITLE
Update versioning to follow semver

### ISSUE THREAD

**Issue by JamiesonRoberts** [pacocoursey/next-themes#79]
To help with issues like the #66 It would be best to update this to use semver. That way consumers of the package can know if there are breaking changes.

EG: when #66 is released the major version would be bumped to say 1.0.0 so that users know that a breaking change has occurred, in this case the breaking change would be that they must be using v12 of NextJS to use it.

**Comment by pacocoursey** [comment]
I released the latest as `0.1.0`. I'll plan to do `1.0.0` in the near future with a few additional features and breaking changes related to #73 and #70
