### ISSUE TITLE
styled-components and any other CSS in JS supported?

### ISSUE THREAD

**Issue by Sporesirius** [pacocoursey/next-themes#8]
Hi,
is styled-components ThemeProvider supported with next-themes or would it be possible?
maybe also styled-jsx, emotion etc.

**Comment by pacocoursey** [comment]
Of course! Next Themes is completely CSS independent. I added a note and example about this [to the README](https://github.com/pacocoursey/next-themes#with-styled-components-and-any-css-in-js).

**Comment by Sporesirius** [comment]
oh, okay thanks. but I mean styled-components and other css in js have a theme system like sc e.g:
`
// Define our button, but with the use of props.theme this time
const Button = styled.button`
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border-radius: 3px;

  /* Color the border and text with theme.main */
  color: ${props => props.theme.main};
  border: 2px solid ${props => props.theme.main};
`;

// We are passing a default theme for Buttons that arent wrapped in the ThemeProvider
Button.defaultProps = {
  theme: {
    main: "palevioletred"
  }
}

// Define what props.theme will look like
const theme = {
  main: "mediumseagreen"
};

render(
  <div>
    <Button>Normal</Button>

    <ThemeProvider theme={theme}>
      <Button>Themed</Button>
    </ThemeProvider>
  </div>
);
`
or do I see something wrong?

**Comment by pacocoursey** [comment]
Libraries like Styled Components are pretty bad because they force you to use a lot of runtime just to use CSS. I'd highly recommend a more static solution like CSS variables.

That being said, nothing is different. In your Custom App:

```js
export default function App({ Component, pageProps }) {
  return (
    <ThemeProvider>
      <StyledComponentsThemeProvider>
        <Component {...pageProps} />
      </StyledComponentsThemeProvider>
    </ThemeProvider>
  )
}

const themeObjects = {
  light: {
    primary: 'blue'
  },
  dark: {
    primary: 'red'
  }
}

const StyledComponentsThemeProvider = ({ children }) => {
  const { theme } = useTheme()

  return (
    <SCThemeProvider
      theme={theme === 'light' ? themeObjects.light : themeObjects.dark}
    >
      {children}
    </SCThemeProvider>
  )
}
```

You can use Next Theme's `useTheme` to get the actual page theme, and pass it along to Styled Components theme handling. You'll have to solve hydration mismatch and flashing yourself, because as mentioned earlier SC relies on runtime and doesn't work well with SSR.

**Comment by MrUltimate** [comment]
Hey @Sporesirius 

Did you ever manage to satisfactorily use this with `styled-components`? Wondering if you were about to iron out the hydration mismatch and flashing issues?

**Comment by douglasrcjames** [comment]
Looking to achieve this with Next.js 13 App directory with styled-components. Any solution for this?
