### ISSUE TITLE
Heading text default black does not toggle

### ISSUE THREAD

**Issue by kaloraat** [pacocoursey/next-themes#80]
It does not seem to work with h1 or h2. Was just playing around with basic html content. Here is the screenshot.
<img width="376" alt="Screen Shot 2022-01-18 at 4 20 19 PM" src="https://user-images.githubusercontent.com/15702617/149875650-d3c1e934-56cd-4d64-b48a-2537dff8b411.png">
<img width="379" alt="Screen Shot 2022-01-18 at 4 20 33 PM" src="https://user-images.githubusercontent.com/15702617/149875652-5aa5bfee-3a06-45a7-a67f-7aa71ce316d2.png">

**Comment by pacocoursey** [comment]
This is an issue with your styling.
