### ISSUE TITLE
Issue With with Persistent Layouts

### ISSUE THREAD

**Issue by MattHeslington** [pacocoursey/next-themes#81]
Hello, 

I'm using the Next Layout component suggested by Vercel at https://github.com/vercel/next.js/tree/canary/examples/layout-component to provide persistent layouts. Unfortunately, next-themes doesn't work with it at all. I have a codesandbox here: https://codesandbox.io/s/small-sky-nylu8

Removing getLayout from the return in _app.js solves the problem, but of course then breaks the persistent layouts:

    function MyApp({ Component, pageProps }) {

        const getLayout = Component.getLayout || ((page) => page)

        return getLayout(
            <ThemeProvider attribute="class">
                <Component {...pageProps} />
             </ThemeProvider>
        )
    }

As a work-around in my project I moved the ThemeProvider from the _app.js file to my layout file. Is this ok to do, or would you suggest another way?

Cheers, Matt

**Comment by pacocoursey** [comment]
Hey, I haven't had the time to look at the Codesandbox yet (thanks for sharing one!) but a simple fix might be to move the `getLayout` inside of `ThemeProvider` instead of how you have it now.

```js
return (
  <ThemeProvider>
    {getLayout(...)}
  </ThemeProvider>
)
```

**Comment by MattHeslington** [comment]
Hi, thanks for the reply. Removing getLayout will break the persistent layout, which I absolutely need. I'm going to just wrap my layout component with the ThemeProvider and see how we go. I've tried it quickly before and it seemed ok. I'll report back

**Comment by pacocoursey** [comment]
Yep, not suggetsing removing `getLayout` but just moving it inside ThemeProvider. Let me know if it works
