### ISSUE TITLE
Theme is not switching at first click.

### ISSUE THREAD

**Issue by arikchakma** [pacocoursey/next-themes#82]
https://www.loom.com/share/2ee6ff707bc44030bc93b62d35b92d88

The theme is changing correctly with the system or toggle, **but when I switch from the system's dark to light mode,** it doesn't work at first click. **On the first click, it saves the value to localStorage, and after that, it changes the theme.**

Is it a bug or something?

Repo: https://github.com/arikchakma/arikkodev

**Comment by pacocoursey** [comment]
Hey, your logic here is wrong: https://github.com/arikchakma/arikkodev/blob/a6f3aed3b5ec42e8e384dd8706ac3617fb68c742/components/Switch.js#L17

This should be comparing against `resolvedTheme`. Otherwise, `theme` can be `system`, so your `=== 'dark'` fails, which you assume to be light.
