### ISSUE TITLE
Add Playwright tests

### ISSUE THREAD

**Issue by pacocoursey** [pacocoursey/next-themes#88]
The number of edge cases in this library is pretty astounding 😅 Let's setup Playwright to do some realistic tests against Chrome, Firefox, and Safari. This would also catch a host of bugs related to navigating between pages with and without forced themes.

We should:
1. Build the examples with the latest code with Vercel against each PR 
2. Run the Playwright tests against the deployed code via GitHub Actions

**Comment by trm217** [comment]
@pacocoursey Happy to help with this, feel free to assign me. :)
