### ISSUE TITLE
Flashing in Firefox on first call and on every refresh

### ISSUE THREAD

**Issue by stffffn** [pacocoursey/next-themes#90]
## Issue
The page flashes on first call and on every page refresh in Firefox with next-themes 0.1.1, if you have dark mode activated in your OS but no current local storage item regarding your theme choice.

This issue was introduced with version 0.0.16, downgrading to 0.0.15 fixes it.

## Setup
SSG Next app with Tailwind. But the same applies if you try it with plain CSS modules.

### 0.0.15
![nextthemes-0015](https://user-images.githubusercontent.com/16480903/155580063-32d62f98-ebe1-43e3-bbda-f3c48cfa5b10.gif)

### 0.1.1
![nextthemes-011](https://user-images.githubusercontent.com/16480903/155581644-b7fd9404-b21b-4db9-a800-cf0e074ac7de.gif)

## Versions
Next 12.1.0
Tailwind 3.0.22
next-themes 0.1.1
Firefox 97.0.1
macOS 12.2.1 (21D62)

**Comment by bte234** [comment]
I am having the same issue. Downgrading to 0.0.15 also solves the flashing.

Versions
Next 12.1.0
Tailwind 3.0.23
next-theme 0.1.1
Firefox 97.0.1 / Chrome 98.0.4758.109
macOS 10.15.7

**Comment by dstroot** [comment]
Seeing in Chrome as well.

**Comment by rminami** [comment]
I'm seeing the same issue in both Firebox and Chrome as well.

- next-themes 0.1.1
- Next.js 12.1.0
- Tailwind 3.0.23
- Chrome 99.0.4844.51 / Firefox 98.0
- macOS 12.2.1

**Comment by TGlide** [comment]
Using next-themes [0.2.0-beta.0](https://www.npmjs.com/package/next-themes/v/0.2.0-beta.0) worked for me

**Comment by stffffn** [comment]
> Using next-themes [0.2.0-beta.0](https://www.npmjs.com/package/next-themes/v/0.2.0-beta.0) worked for me, in Firefox, Chrome and Safari.

I tested it right now and unfortunately it doesn't fix the issue in Firefox (updated to 98.0 in the meantime).  
It works only in Chrome (99.0.4844.51) and Safari (15.3) but I didn't have any issues in both browsers with next-themes 0.1.1 anyway. It only affects Firefox.

**Comment by siddiquiehtesham** [comment]
I had the same issue, I downgraded to `v0.0.15` and it seems to work as expected.

One side note: I see flashing screen in Firefox only when I run in dev mode `yarn dev`, though it works ok in chrome and safari in dev mode
The problem goes away with the build version (`yarn build && yarn start`). Works in all browsers

**Comment by pacocoursey** [comment]
Flashing in development is expected:

https://github.com/pacocoursey/next-themes#faq

**Comment by siddiquiehtesham** [comment]
> Flashing in development is expected:
> 
> https://github.com/pacocoursey/next-themes#faq

Yes I forgot to mention this FAQ link, it was a reference for others who are not aware of the behaviour.
