### ISSUE TITLE
Scripts inserted using next/head warning?

### ISSUE THREAD

**Issue by lazarusking** [pacocoursey/next-themes#93]
I kept getting this warning and after commenting out `<ThemeProvider/>` from my _app.js , it disappeared.
Seems next-themes is the culprit if I'm not wrong.
 
![image](https://user-images.githubusercontent.com/28906424/156862372-4e1b4b16-8085-4a45-baf9-a22e2769c900.png)

**Comment by hodela** [comment]
You are using old version next-themes, open package.json file and change next-themes to latest ("next-themes": "latest"). Then run yarn install again

**Comment by lazarusking** [comment]
npm update/install kept installing the old version for some reason, thanks 👍
