### ISSUE TITLE
Theme flashing 

### ISSUE THREAD

**Issue by cdfornari** [pacocoursey/next-themes#97]
I tried latest and 0.0.15 versions in production build, it keeps flashing.
<img width="701" alt="Screen Shot 2022-03-30 at 10 22 42 PM" src="https://user-images.githubusercontent.com/64043046/160963648-b42e40d6-865b-4f8d-96a2-40e07eb90cd3.png">

**Comment by pacocoursey** [comment]
#90

**Comment by cdfornari** [comment]
None of those solutions solved the issue for me
