### ISSUE TITLE
ThemeChange Event

### ISSUE THREAD

**Issue by MDrooker** [pacocoursey/next-themes#98]
Is there a way to fire an event on the ```<ThemeProvider>``` when the theme actually changes from deep in the app?

Wanting to track the metric event of users changing theme in one place.

**Comment by pacocoursey** [comment]
You could register a hook that listens for changes to the `theme`:

```ts
const useThemeChange = () => {
  const initial = useRef(true)
  const { theme } = useTheme()

  useEffect(() => {
    if (initial.current) {
      initial.current = false
      return
    }

    // theme changed, record analytics
  }, [theme])
}

```
